import type {
  TimelineCopy, StudioCopy, JournalCopy, CircleCopy,
  NoticeCopy, TicketCopy, BookCopy, CompanionCopy, PrepCopy, VenueCopy, EnvelopesCopy, VehiclesCopy,
  MeetingTemplatesCopy,
} from './appUi.ts';
import type {
  PortalCopy, FilesCopy, SheetsCopy, TasksCopy, MoneyCopy, BoardCopy,
  GuestsCopy, SeatingCopy, DayCopy, ThreadCopy, PartyCopy, ContractCopy, EventFileCopy,
} from './appUi.ts';

/**
 * The couple's own area, in English.
 *
 * Only what a couple sees. The producer's screens stay Hebrew: there is one
 * producer, he works in Hebrew, and translating the admin would be work nobody
 * reads. Where a block is shared between the two sides, only the sentences
 * addressed to the couple were written with them in mind; the producer's
 * variant of the same key is translated too, because the type demands the
 * whole block and a half translated object is worse than none.
 *
 * Same guarantee as the public site: every type here is the Hebrew block put
 * through `Wide<>`, so the keys, the nesting and the tuple lengths have to
 * match exactly and only the words are free.
 */

export const portalEn: PortalCopy = {
  title: 'Our area',
  guestSite: {
    title: 'The link for your guests',
    sub: 'Send it on WhatsApp to everyone invited. Each guest finds themselves by phone number and replies.',
    copy: 'Copy the link',
    copied: 'Copied',
    open: 'Open the page',
    share: 'Share on WhatsApp',
    shareText: 'You are invited to celebrate with us! All the details and the RSVP are here:',
  },
  sub: 'Everything about your event, in one place.',
  empty: 'No event has been linked to you yet. The production will open it and you will hear from us.',
  emptyWho: 'You are signed in as {email}.',
  emptyMismatch:
    'If the invitation went to a different address, that is why this screen is empty. You can sign out '
    + 'and sign in with the address the invitation arrived at, or simply write to us and we will '
    + 'attach this address to the event.',
  daysLeft: 'days to the wedding',
  dateTbd: 'The date is not set yet',
  summary: 'A quick look',
  rowBudget: 'Budget',
  rowRsvp: 'Replies',
  rowBoard: 'Inspiration',
  rowVendors: 'Suppliers',
  eventAdd: 'Add an event',
  eventPick: 'Your events',
  rowTasks: 'Open tasks',
  rowNone: 'Not entered yet',
  rowPayments: 'Still to pay',
  rowSeating: 'Tables',
  rowContracts: 'Contracts',
  rowVenues: 'Halls to compare',
  rowFiles: 'Files and photos',
  rowLists: 'Songs, kit and details',
  rowPrep: 'Faces and looks',
  rowEnvelopes: 'Envelopes',
  rowTransport: 'Cars and rides',
  rowThread: 'Messages',
  rowMeetings: 'Meeting notes',
  meetings: {
    title: 'Meeting notes',
    sub: 'What was agreed in the meetings shared with you. Read only; questions about them go in the messages below.',
    none: 'No meeting summary has been shared with you yet.',
    untitled: 'Meeting',
    noSummary: 'The meeting was recorded without a summary.',
  },
  rowRunsheet: 'The day\'s schedule',
  next: {
    title: 'What now',
    by: 'by',
    late: 'Overdue',
    noDue: 'No date',
    also: 'After that',
    ownerUs: 'Ours',
    ownerProducer: 'Production',
    go: {
      tasks: 'To the tasks',
      payments: 'To the payments',
      guests: 'To the guest list',
      budget: 'To the budget',
      board: 'To the inspiration board',
    },
    say: {
      payLate: { head: 'Settle the payment: {s}', why: 'The date set for this payment has passed.' },
      taskLate: { head: '{s}', why: 'This task is past the date set for it.' },
      paySoon: { head: 'A payment is coming up: {s}', why: 'Worth making sure the money is ready for the date.' },
      taskSoon: { head: '{s}', why: 'This is the nearest task on your list.' },
      guestsChase: { head: 'Remind whoever has not replied', why: '{n} guests have not answered, and the venue needs a number.' },
      guestsEmpty: { head: 'Start the guest list', why: 'Every other figure comes from it: how many plates, how many tables, how much it costs.' },
      budgetOver: { head: 'The {s} budget is past the plan', why: 'Worth seeing where to make it up before another supplier is booked.' },
      budgetEmpty: { head: 'Break the budget into lines', why: 'There is a target, and nothing yet showing where it goes.' },
      boardEmpty: { head: 'Save a few pictures you liked', why: 'The look of the evening starts there, and it is what suppliers are shown.' },
      start: { head: 'Add the first task', why: 'Nothing has been written down yet. Anything you put here, the production sees too.' },
      clear: { head: 'All handled', why: 'No task, payment or reply is waiting on you right now.' },
    },
    moreTasks: 'and {n} more overdue',
  },
  begin: {
    title: 'A few things about your wedding',
    sub: 'Five short questions. Any of them can be skipped, and anything you do not know yet stays open.',
    of: 'Question {n} of {of}',
    skip: 'Not decided yet',
    back: 'Back',
    next: 'Next',
    finish: 'Done',
    saving: 'Saving',
    failed: 'Could not save. You can try again.',
    open: 'Start',
    later: 'Not now',
    q: {
      date: { head: 'When is the wedding', hint: 'If there is no final date yet, that is fine.' },
      guests: { head: 'Roughly how many guests', hint: 'A rough estimate is enough. The venue, the plates and the tables all come from it.', ph: 'say 180' },
      region: { head: 'Roughly where', hint: 'An area, not a venue. The hall is chosen later.', ph: 'say the north' },
      budget: { head: 'What figure do you have in mind', hint: 'A starting number. It can change at any point.', ph: 'say 250,000' },
      priorities: { head: 'What will you not compromise on', hint: 'Up to three. Whatever you pick gets a larger share of the budget.' },
    },
    doneTitle: 'Saved',
    doneTasks: '{n} first tasks were added to your list.',
    doneNone: 'It was all recorded already, so there was nothing to add.',
    wrote: {
      date: 'Date',
      guests: 'Guest count',
      region: 'Area',
      budget: 'Budget',
      plan: 'Priorities',
    },
  },
  nav: 'Jump to a section',
  vendorsTitle: 'Our suppliers',
  vendorsSub: 'Who is booked and who is still being looked at. A supplier you tick off in the tasks lands here by itself.',
  vendorsEmpty: 'No supplier booked yet. Tick one off in the tasks and it appears here with their number.',
  vendorBooked: 'Booked',
  vendorShortlist: 'Being looked at',
  vendorCancelled: 'Cancelled',
};

export const filesEn: FilesCopy = {
  title: 'Files and photographs',
  subClient: 'Everything you wanted to send us and had nowhere to put. Photographs, the invitation, a list, a plan from the venue.',
  subProducer: 'The shared folder for this event. What the couple uploaded and what you uploaded for them.',
  add: 'Add files',
  adding: 'Uploading',
  drop: 'Drag them here, or choose from your device',
  dropHint: 'Up to 50MB a file. Images, PDF, Word, Excel, video and audio.',
  none: 'Nothing here yet.',
  noneProducer: 'No files have been uploaded to this event yet.',
  open: 'Open',
  download: 'Download',
  remove: 'Remove',
  note: 'Note',
  notePh: 'What this file is',
  noteSave: 'Save',
  by: 'Uploaded by',
  photos: 'Photographs',
  documents: 'Documents',
  tooBig: 'That file is too large. Up to 50MB.',
  badType: 'That file type is not supported',
  failed: 'The upload failed. Please try again.',

  media: {
    title: 'Photographs',
    sub: 'The venue, the design, the inspiration and the suppliers. Every picture carries a tag, so it can still be found after the sixtieth.',
    tagForUpload: 'Tag for the pictures you are adding now',
    all: 'All',
    untagged: 'Untagged',
    tags: {
      venue: 'Venue',
      design: 'Design',
      inspiration: 'Inspiration',
      vendors: 'Suppliers',
    },
    count: '{n} photographs',
    one: 'One photograph',
    none: 'No photographs under this tag yet.',
    open: 'Enlarge',
    close: 'Close',
    prev: 'Previous',
    next: 'Next',
    retag: 'Change tag',
    manage: 'Manage',
    done: 'Done',
  },
};

export const sheetsEn: SheetsCopy = {
  close: 'Close',
  contact: {
    open: 'Talk to the producer',
    title: 'Your producer',
    sub: 'Available Sunday to Thursday, 09:00 to 19:00',
    call: 'Phone call',
    whatsapp: 'WhatsApp message',
    whatsappMeta: 'Answered within the hour',
    meeting: 'Book a meeting',
    meetingMeta: 'Open slots in the diary',
  },
  report: {
    open: 'Report a problem',
    title: 'Report a problem',
    sub: 'The report goes straight to the production desk and is recorded on the event.',
    topics: ['Timing and schedule', 'A supplier is not answering', 'Payment', 'Replies', 'Something broken in the app', 'Something else'],
    placeholder: 'What happened? Add any detail you have',
    submit: 'Send the report',
    sending: 'Sending…',
    sent: 'The report reached the desk',
    failed: 'We could not send it. Please try again.',
    empty: 'Please write what happened',
  },
};

export const tasksEn: TasksCopy = {
  reorder: 'Drag to reorder',
  title: 'Tasks',
  subProducer: 'A shared list. Both sides see it and either side can tick something off.',
  subClient: 'What is left to do, and what is already settled.',
  add: 'Add a task',
  adding: 'Adding',
  titlePh: 'What needs doing',
  due: 'By when',
  owner: 'Whose',
  ownerProducer: 'Ours',
  ownerClient: 'Yours',
  ownerProducerClientView: 'Production',
  ownerClientClientView: 'Ours',
  none: 'No tasks yet.',
    planTitle: 'Start from a full plan',
    planBody: 'Twenty-eight steps dated backwards from the event, from a year before to a month after. All of it editable, and nothing you already have is overwritten.',
    planCta: 'Build the plan for me',
    planBusy: 'Building',
    planDone: 'The plan is in',
    planEmpty: 'Every step is already on this event.',
  open: 'Open',
  done: 'Done',
  overdue: 'Overdue',
  noDue: 'No date',
  remove: 'Delete',
  byProducer: 'Written by the production',
  byClient: 'Written by the couple',
};

export const moneyEn: MoneyCopy = {
  ledger: {
    title: 'What is left',
    sub: 'What comes in, what goes out, and what remains. Only you see this.',
    billed: 'Billed to the couple',
    received: 'Received',
    outstanding: 'Still owed',
    suppliers: 'Suppliers',
    crew: 'Crew',
    costs: 'Total out',
    margin: 'Remaining',
    marginPct: '{n}% of billing',
    loss: 'This event is running at a loss',
    early: 'There are costs recorded and nothing billed yet. That is the normal state before the final invoice goes out, so there is no bottom line here yet.',
    none: 'No figures on this event yet.',
  },
  payTitle: 'Payments',
  paySubProducer: 'What the couple has paid and what is still open. They see this, and only you mark something paid.',
  paySubClient: 'What has been paid and what is still open.',
  payWhat: 'What for',
  payWhatPh: 'Deposit',
  payAmount: 'Amount',
  payDue: 'Due by',
  payAdd: 'Add a payment',
  payAdding: 'Adding',
  payNone: 'No payments recorded yet.',
  paid: 'Paid',
  unpaid: 'Open',
  overdue: 'Overdue',
  totalPaid: 'Paid',
  totalOwed: 'Still to pay',
  totalAll: 'Total',
  markPaid: 'Mark as paid',
  markUnpaid: 'Undo that mark',
  remove: 'Delete',
  noDue: 'No date',

  budTitle: 'Budget',
  budSub: 'The estimate against what was actually agreed, item by item.',
  budLabel: 'Item',
  budLabelPh: 'Catering',
  budCategory: 'Category',
  budVendor: 'Supplier',
  budEstimate: 'Estimate',
  budAgreed: 'Agreed',
  budAdd: 'Add an item',
  scan: 'Photograph a receipt',
  scanning: 'Reading the receipt',
  scanHint: 'Photograph a supplier receipt and the fields fill themselves. Nothing is saved until you press add.',
  scanFilled: 'Filled in from the receipt. Check it and add it.',
  scanUnsure: 'I filled in what I could read, but not all of it was clear. Worth checking the amount.',
  scanFailed: 'I could not read the image. You can fill it in by hand.',
  scanTooBig: 'That image is too large. Try photographing it again.',
  budNone: 'No budget items recorded yet.',
  budTotalEst: 'Total estimate',
  budTotalAgreed: 'Total agreed',
  budDiff: 'Difference',
  budUnder: 'under the estimate',
  budOver: 'over the estimate',

  finance: {
    title: 'The money at a glance',
    sub: 'Five figures, and how we got to each.',
    how: 'How it is worked out',
    formula: 'How is the budget worked out? The sum of every agreed supplier cost, minus the deposits already paid, is the balance left to pay by the day. The margin is the target budget minus the commitments.',
    target: 'Target budget',
    targetSub: 'The ceiling you agreed on together',
    noTarget: 'Not set',
    committed: 'Committed costs and contracts',
    committedSub: 'Every line at its agreed price, or its estimate until agreed',
    paid: 'Paid so far / deposits',
    paidSub: 'What has already left the account',
    remaining: 'Remaining balance',
    remainingSub: 'Commitments minus what was paid',
    variance: 'Margin / overrun',
    surplus: 'Safety margin',
    overrun: 'Over budget',
    underBadge: 'Within budget',
    overBadge: 'Over budget',
    setTargetFirst: 'Set a target budget',
    paidShare: 'Paid',
    pendingShare: 'Pending',
    setTarget: 'Set a target budget',
    editTarget: 'Change the target',
    save: 'Save',
    saving: 'Saving',
    cancel: 'Cancel',
  },
  budShow: 'The couple sees the budget',
  budHidden: 'Hidden from the couple',
  budVisible: 'Visible to the couple',
  budHiddenNote: 'The budget is hidden from the couple. You can open it to them at any point.',
  plan: {
    title: 'The budget plan',
    sub: 'How the total splits between the areas, by what matters to you. What is actually booked is measured against it, and every Sunday morning a summary goes out.',
    open: 'Build a budget plan',
    close: 'Close',
    total: 'Total budget',
    guests: 'Guest count',
    pick: 'What matters to you',
    pickHint: 'For each area: normal, non-negotiable, or could cut. A non-negotiable goes up by a quarter, a could-cut goes down by forty percent, and the rest gives or takes so the total stays at one hundred.',
    neutral: 'Normal',
    must: 'Non-negotiable',
    nice: 'Could cut',
    categories: {
      venue: 'Venue and catering',
      bar: 'Bar and alcohol',
      photo: 'Photo and video',
      music: 'Music',
      design: 'Design and flowers',
      look: 'Attire, makeup and hair',
      invites: 'Invitations and replies',
      transport: 'Transport',
      other: 'Other',
      contingency: 'Safety margin',
    },
    colArea: 'Area',
    colBase: 'Baseline',
    colPct: 'Yours',
    colAmount: 'Amount',
    colWhy: 'Why',
    reasonMust: 'Up from {from}% to {to}% because you marked it non-negotiable.',
    reasonNice: 'Down from {from}% to {to}% because you marked it as something to cut.',
    reasonShift: 'Adjusted from {from}% to {to}% so the total stays at one hundred percent.',
    reasonSame: 'As the baseline.',
    perHead: 'About {n} a plate at the venue. One number to check against the quote.',
    basis: 'The baseline is the Israeli split: venue and catering are sold together, per plate. The safety margin never drops below five percent, because it is what turns a surprise into an inconvenience rather than a problem.',
    save: 'Save the plan',
    saving: 'Saving',
    saved: 'The plan is saved. From now on every line is measured against it.',
    failed: 'Could not save',
    trackerTitle: 'Budget tracker',
    trackerSub: 'Planned against booked, by area. The red row is the safety margin: when it is gone, it is gone.',
    trackerNoPlan: 'No plan yet, so there is only what is booked. Build a plan and every line is measured against something.',
    colPlanned: 'Planned',
    colActual: 'Booked',
    colRemaining: 'Left',
    colUsed: 'Used',
    colNotes: 'Notes',
    lines: { one: 'One line', many: '{n} lines' },
    nothingBooked: 'Nothing booked yet',
    overTitle: 'Over: {cat} is {pct}% above plan',
    overBody: '{actual} booked against {planned} planned.',
    tradeOff: 'Suggestion: trim {cat}, where {amount} is still unspent.',
    tradeOffNone: 'No area has the room to absorb this. Either the budget goes up, or something booked comes down.',
    weekTitle: 'The bottom line this week',
    overall: 'Commitments of {committed} against {target}, {pct}% of the budget.',
    overallNoTarget: 'Commitments of {committed}. No target budget set yet.',
    watch: 'Keep an eye on {cat}: {pct}% of the plan is already booked.',
    watchNone: 'No area needs watching this week.',
    nextDue: 'Next payment: {title}, {amount}, by {date}.',
    nextDueNone: 'No payment due in the next thirty days.',
    digestNote: 'Every Sunday morning a summary like this goes out by email, to you and to the couple if the budget is open to them, with what was added and what was paid that week.',
  },
};

export const boardEn: BoardCopy = {
  eyebrow: 'Inspiration',
  title: 'Inspiration board',
  subClient: 'The photographs that made you say "that is the one". Everything collected here goes to the suppliers with us.',
  subProducer: 'The photographs the couple collected. Read only, they manage the board from their own area.',
  upload: 'Upload a photograph',
  choose: 'Choose a photograph',
  uploading: 'Uploading',
  caption: 'Caption',
  captionPh: 'What you liked here',
  category: 'Category',
  all: 'All',
  none: 'Nothing on the board yet.',
  noneProducer: 'The couple has not uploaded anything yet.',
  remove: 'Remove',
  tooBig: 'That image is too large. Up to 8MB.',
  chooseMany: 'Choose photographs',
  picked: { one: 'One photograph chosen', many: '{n} photographs chosen' },
  progress: 'Uploading {n} of {m}',
  failedSome: { one: 'One photograph did not upload', many: '{n} photographs did not upload' },
  dropHint: 'Choose several at once, or drag them here. The caption and the category apply to all of them.',
  subProducerAdd: 'The photographs the couple collected, and what you added for them. The brand reading works on what is here.',
};

export const guestsEn: GuestsCopy = {
  title: 'Replies',
  sub: 'The guest list and their answers. Every guest gets a personal link.',
  attending: 'Coming',
  declined: 'Not coming',
  pending: 'No answer yet',
  invited: 'Invited',
  heads: 'Total people',
  showOnly: 'Show in the list',
  addTitle: 'Add guests',
  addHint: 'One name a line. "Name, side, phone" works too.',
  addPh: 'The Cohen family, bride, 0501234567\nDavid and Ronit\nYael from work',
  side: 'Side (default)',
  add: 'Add to the list',
  adding: 'Adding',
  none: 'No guests added yet.',
  copyLink: 'Copy the link',
  copied: 'Copied',
  remind: 'Remind',
  remindText: 'Hi {name}, we would love to know if you can make it to our wedding. You can answer here: {url}',
  remove: 'Remove',
  markAttending: 'Mark coming',
  markDeclined: 'Mark not coming',
  markPending: 'Reset',
  guest: 'Guest',
  status: 'Answer',
  party: 'People',
  dietCol: 'Food',
  noteCol: 'Note',
};

export const seatingEn: SeatingCopy = {
  dragHint: 'Drag a guest onto a table, or use the picker. A table with no room will not take the drop.',
  title: 'Seating',
  sub: 'Only people who replied get a seat. A table will not seat more people than it has chairs.',
  addTable: 'New table',
  tableName: 'Name',
  tableNamePh: 'Table 1',
  seats: 'Seats',
  add: 'Add',
  adding: 'Adding',
  noTables: 'No tables added yet.',
  seated: 'Seated',
  free: 'Free',
  full: 'Full',
  emptyTable: 'Nobody at this table yet.',
  unseated: 'Waiting to be seated',
  unseatedNone: 'Everybody who replied has a seat. 🎉',
  place: 'Seat at',
  choose: 'Choose a table',
  unseat: 'Take off the table',
  removeTable: 'Delete the table',
  removeTableHint: 'The guests are not deleted, they go back to the waiting list.',
  peopleShort: 'people',
  needRsvp: 'Nobody has replied yet. Seat people once the answers start coming in.',
  floor: 'Floor plan',
  floorSub: 'Every circle is a table and every dot around it is a chair. A taken chair is marked in gold.',
  openTable: 'Open the table',
  seatFree: 'Free chair',
};

export const dayEn: DayCopy = {
  moveUp: 'Move earlier',
  moveDown: 'Move later',
  dragHint: 'You can also drag a row up or down',
  audience: 'Who this schedule is for (empty = everybody):',
  title: 'The day itself',
  sub: 'The morning looks different for each of you, so each of you has their own track, and what is shared sits in the middle.',
  shared: 'Shared',
  addTitle: 'What happens',
  addTitlePh: 'Hair and makeup',
  time: 'Time',
  note: 'Note',
  notePh: 'Where, with whom',
  track: 'Track',
  add: 'Add to the schedule',
  adding: 'Adding',
  none: 'No schedule built for the day yet.',
  emptyTrack: 'Nothing on this track yet.',
  remove: 'Delete',
  rename: 'Rename the tracks',
  renameSave: 'Save the names',
  renameHint: 'What you call the two tracks. These names are yours.',

  owner: 'Who is responsible',
  ownerPh: 'Name',
  duration: 'How long',
  durationPh: 'min',
  untilNext: 'until the next',
  edit: 'Edit',
  save: 'Save',
  cancel: 'Cancel',
  addOpen: 'Add a row',
  addClose: 'Close',
  overlap: 'Overlaps "{title}" on the same track',
  crossesMidnight: 'The schedule runs past midnight, and the rows are ordered by the evening rather than by the clock.',
  totalLines: '{n} rows',
  span: '{from} to {to}',

  templateTitle: 'Start from a ready schedule',
  templateSub: 'Pick a starting point, then delete and change whatever does not fit. Only available while the schedule is empty.',
  templateApply: 'Open the schedule',
  templateApplying: 'Opening',
  templateOr: 'or start from an empty row',
  keyMoment: 'Key moment',
  keyMomentHint: 'The desk will warn 10 minutes before',
};

export const threadEn: ThreadCopy = {
  title: 'Messages',
  sub: 'Everything agreed about the event, in one place that stays with it.',
  empty: 'No messages yet. Write the first one.',
  placeholder: 'Write a message',
  send: 'Send',
  sending: 'Sending',
  retract: 'Delete',
  today: 'Today',
  yesterday: 'Yesterday',
};

export const partyEn: PartyCopy = {
  name: 'Name of the other party',
  namePh: 'The supplier or the couple',
  role: 'Role',
  rolePh: 'DJ, photographer, officiant',
};

export const contractEn: ContractCopy = {
  title: 'Agreements',
  subProducer: 'A draft stays with you. Once it is sent the couple sees it, and once it is signed the terms stop moving.',
  subClient: 'What was agreed, written down. Signing here carries the same weight as signing on paper.',
  newContract: 'New agreement',
  cancel: 'Cancel',
  untitled: 'Untitled agreement',
  titleLabel: 'Name of the agreement',
  titlePh: 'Wedding production agreement',
  amountLabel: 'Amount',
  amountPh: 'Amount in shekels',
  bodyLabel: 'Terms',
  bodyPh: 'The fee, the payment schedule, what is included and what is not, cancellation terms.',
  attach: 'Attach a document',
  attached: 'The document is attached',
  uploading: 'Uploading',
  tooBig: 'That file is too large. Up to 20MB.',
  uploadFailed: 'The upload failed. Please try again.',
  saveDraft: 'Save the draft',
  saving: 'Saving',
  draftHint: 'The couple cannot see the draft until you send it.',
  send: 'Send for signature',
  discard: 'Delete',
  void: 'Void the agreement',
  openDoc: 'Open the attached document',
  signedBy: 'Signed by',
  signIntro: 'Read the terms? Sign with your full name to confirm.',
  signNameLabel: 'Full name for the signature',
  signNamePh: 'Full name',
  sign: 'Sign',
  signing: 'Signing',
  signLegal: 'The signature is recorded with the name, the date and the time, and with a fingerprint of the text that was signed. Once signed, the terms cannot be changed.',
  tampered: 'The text shown here is not the text that was signed. Do not rely on it, contact the producer.',
  emptyProducer: 'No agreement has been created for this event yet.',
  emptyClient: 'No agreement has been sent to you yet.',
  status: {
    draft: 'Draft',
    sent: 'Waiting for signature',
    signed: 'Signed',
    void: 'Void',
  },
};

export const eventFileEn: EventFileCopy = {
  music: {
    title: 'Music',
    sub: 'Seven moments that need a song. The list goes to the DJ exactly as it is.',
    song: 'Song',
    songPh: 'Name of the song',
    artist: 'Artist',
    note: 'Note',
    notePh: 'Which version, how long, where to stop',
    save: 'Save',
    chosen: '{n} of {of} chosen',
    empty: 'No song chosen for any moment yet.',
  },

  equipment: {
    title: 'Equipment',
    sub: 'What is needed, and what is already settled.',
    undecided: 'Not looked at yet',
    off: 'Not needed',
    needed: 'Needed',
    sorted: 'Settled',
    openCountOne: 'One item open',
    openCountMany: '{n} items open',
    allSorted: 'All settled.',
  },

  couple: {
    title: 'Personal details',
    sub: 'What makes a wedding theirs. The couple fills it in and you see it.',
    personA: 'One of you',
    personB: 'The other',
    name: 'Name',
    namePh: 'What they are called',
    save: 'Save',
    saved: 'Saved',
    emptyHint: 'Empty. You can fill it in here, or ask the couple to fill it in from their own area.',
  },
};

/* Their producer's voice in English. Same rule as the Hebrew: nothing here
   may sound like a product, so the title is what it answers rather than what
   it is. */
export const companionCopyEn: CompanionCopy = {
  title: 'Questions about the wedding',
  sub: 'Answers from your own event details',
  open: 'Open a conversation',
  close: 'Close',
  greeting: 'Ask me what is left for you to do, how many have replied, when the next payment is due, and how the evening runs.',
  starters: ['What is left for us?', 'How many have replied?', 'When is the next payment?'],
  placeholder: 'What would you like to know',
  send: 'Send',
  thinking: 'Writing',
  wentWrong: 'Something went wrong at my end. Write to us and we will come back to you.',
  disclaimer: 'Answers come from your event details. Changes go through us.',
};

/* The faces and the looks, in English.
   Addressed to the couple rather than to the producer: they are the ones who
   know who the aunt is, and on their screen "the photographer does not know
   anybody in the room" is the whole reason the panel exists. */
export const prepCopyEn: PrepCopy = {
  facesTitle: 'Who not to miss',
  facesSub: 'A face and a name for everyone who has to be in the photographs. The photographer does not know anybody in the room.',
  facesEmpty: 'Nobody added yet. Grandma is a good place to start.',
  name: 'Name',
  relation: 'Who they are',
  relationPh: "The bride's grandmother",
  note: 'Note',
  notePh: 'A photograph with her on the way into the ceremony',
  photo: 'Photograph',
  add: 'Add',
  adding: 'Adding',
  remove: 'Remove',

  looksTitle: 'Hair, makeup and outfit references',
  looksSub: 'The pictures saved on your phone, in one place you can send to the stylist.',
  looksEmpty: 'No pictures yet.',
  kind: 'Kind',
  categories: { hair: 'Hair', makeup: 'Makeup', outfit: 'Outfit', other: 'Other' },

  shareTitle: 'A link for a supplier',
  shareSub: 'The photographer and the stylist are not going to open an account to look at pictures. One link, no password, and each of them gets only what concerns them.',
  shareAll: 'Everything',
  shareFaces: 'For the photographer',
  shareLooks: 'For the stylist',
  shareNew: 'New link',
  shareCopy: 'Copy',
  shareCopied: 'Copied',
  shareWhatsapp: 'Send on WhatsApp',
  shareRevoke: 'Revoke',
  shareNone: 'No link yet.',
  shareUntil: 'Valid until',
  uploadFailed: 'The upload failed. You can try again.',
  tooBig: 'That picture is too large. Up to 8MB.',
};

/* The halls, in English. Written for the couple: they are the ones who walked
   round four of them and were handed four numbers that do not mean the same
   thing. */
export const venueCopyEn: VenueCopy = {
  title: 'Comparing venues',
  sub: 'Every quote you were given, broken into the parts that actually differ. The figure at the bottom is what the evening really costs.',
  empty: 'No venue added yet. The last one you saw is a good place to start.',
  emptySub: 'The plate price is enough to begin with. The rest can wait until after you have called them.',

  add: 'Add a venue',
  adding: 'Adding',
  save: 'Save',
  saving: 'Saving',
  edit: 'Edit',
  remove: 'Remove',
  cancel: 'Cancel',

  name: 'Venue',
  namePh: 'The Courtyard',
  location: 'Area',
  locationPh: 'Sharon',
  contact: 'Contact',
  phone: 'Phone',
  toured: 'Date of the tour',
  notes: 'Impressions',
  notesPh: 'Parking, access, acoustics, how flexible they are about hours',

  plate: 'Price per plate',
  vatIncluded: 'This price includes VAT',
  bar: 'Bar and alcohol',
  barFlat: 'Flat fee',
  barPerPerson: 'Per guest',
  sound: 'Sound and lighting',
  ancillary: 'Ancillary fees',
  ancillaryHint: 'Cleaning, security, air conditioning, a screen, the chuppah, extra hours',
  servicePercent: 'Service charge, per cent',
  serviceFlat: 'Flat gratuity',
  quote: 'Their quote',
  quoteOpen: 'Open the quote',

  guests: 'Guests',
  guestsHint: "This is the event's guest estimate. Changing it here changes it in the bar calculator and the budget too.",
  vatBasis: 'Show prices including VAT',
  vatOffNote: 'The budget line is always written including VAT, even while the screen is showing prices without it.',

  food: 'Catering',
  service: 'Service',
  total: 'Total',
  buffer: 'Buffer',
  withBuffer: 'With the buffer',
  perGuest: 'Real cost per guest',
  perGuestHint: 'Once the fixed fees are spread across everyone coming.',
  overCheapest: '{n}% more than the cheapest',

  bestValue: 'Best value',
  chosen: 'The chosen venue',
  choose: 'Choose this venue',
  chooseHint: 'The venue goes onto the event and the figure becomes the baseline line in the budget. The other quotes stay here to look back at.',

  flags: 'What is there',
  flagLabels: {
    licence: 'Business licence in date',
    kosher: 'Kosher certification',
    volume: 'Volume limit after 23:00',
    suite: 'Couple\'s suite',
    generator: 'Backup generator',
    parking: 'Parking',
    accessible: 'Step-free access',
  },

  print: 'Print',
  printHint: 'One landscape page, for the parents.',
  uploadFailed: 'The upload failed. You can try again.',
  tooBig: 'That file is too large. Up to 10MB.',
};

export const noticeCopyEn: NoticeCopy = {
  title: 'Updates',
  none: 'Nothing new.',
  noneSub: 'When something happens on your event, it will appear here.',
  markAll: 'Mark all as read',
  markOne: 'Mark as read',
  open: 'Open',
  close: 'Close',
  unread: 'unread',
  now: 'just now',
  minutes: '{n} min ago',
  hours: '{n} h ago',
  days: '{n} days ago',
  kinds: {
    lead: 'Enquiry',
    rsvp: 'RSVP',
    task: 'Task',
    payment: 'Payment',
    invite: 'Access',
    message: 'Message',
    contract: 'Contract',
    file: 'File',
    order: 'Order',
    anniversary: 'Anniversary',
    meeting: 'Meeting',
    ticket: 'Report',
  },
};

export const ticketCopyEn: TicketCopy = {
  open: 'Report a problem',
  title: 'Report a problem',
  sub: 'Something not working as it should? Tell us what happened and we will look into it.',
  category: 'What kind of problem',
  categories: {
    visual: 'Something looks wrong',
    auth: 'Signing in',
    data: 'Wrong numbers or data',
    other: 'Other',
  },
  body: 'What happened',
  bodyPh: 'What you tried to do, what you expected, and what happened instead',
  screenshot: 'Screenshot',
  screenshotHint: 'Optional. An image up to 5MB.',
  screenshotRemove: 'Remove',
  auto: 'The screen address and your browser are attached automatically, so we can reproduce it.',
  inContext: 'Reporting on: {what}',
  openHere: 'Something wrong here?',
  submit: 'Send the report',
  sending: 'Sending',
  sent: 'Received. We will get back to you.',
  sentSub: 'Your report was saved and sent to the team. If we need more detail, we will write to the address you are signed in with.',
  empty: 'Please write what happened',
  tooBig: 'The screenshot is too large. Up to 5MB.',
  badType: 'A screenshot has to be an image.',
  failed: 'We could not send that. Please try again.',
  close: 'Close',
  admin: {
    title: 'Problem reports',
    sub: 'What people reported from inside the platform. Open ones first.',
    none: 'No open reports.',
    open: 'Open',
    closed: 'Resolved',
    markClosed: 'Mark resolved',
    reopen: 'Reopen',
    route: 'Screen',
    agent: 'Browser',
    screenshot: 'Screenshot',
    reporter: 'Reported by',
    showClosed: 'Show resolved',
  },
};

export const bookEn: BookCopy = {
  title: 'Production book',
  sub: 'The whole event on one document, for printing and for the folder.',
  print: 'Print',
  back: 'Back to the event',
  noDate: 'No date',
  countdown: 'To go',
  days: '{n} days',
  today: 'Today',
  daysAgo: '{n} days ago',
  stage: 'Stage',
  behind: '{n} behind',
  ahead: '{n} ahead',
  heads: 'Covers',
  suppliers: 'Suppliers',
  reachCouple: 'Reach the couple',
  arrivals: 'Who arrives when',
  noArrivals: 'No call times set yet.',
  runningOrder: 'Running order',
  noOrder: 'No running order yet.',
  noSuppliers: 'No suppliers yet.',
  uncategorised: 'Uncategorised',
  vendorStatus: { shortlist: 'Shortlist', booked: 'Booked', cancelled: 'Cancelled' },
  guests: 'Guests',
  invited: 'Invited',
  coming: 'Coming',
  declined: 'Not coming',
  pending: 'No reply',
  diets: 'Dietary',
  open: 'Still open',
  noOpen: 'Nothing left open.',
  noDue: 'No date',
  money: 'Money',
  paid: 'Paid',
  owed: 'Outstanding',
  printedOn: 'Printed',
  phase: {
    foundation: 'Foundations', bookings: 'Bookings', experience: 'Guest experience',
    guests: 'Guest operations', final: 'Final coordination', dayOf: 'The day', after: 'After',
  },
};

export const envelopesCopyEn: EnvelopesCopy = {
  title: 'Envelopes',
  sub: 'The cash you bring on the night: who each one is for, how much, and what has been handed over.',
  empty: 'No envelopes yet. Once you add them, the event manager sees them here on the day.',
  label: 'For',
  labelPh: 'Rabbi, crew tip, photographer',
  recipient: 'Handed to',
  recipientPh: 'A name, if there is one',
  amount: 'Amount',
  how: 'How',
  cash: 'Cash',
  transfer: 'Transfer',
  note: 'Note',
  notePh: 'After the ceremony, for example',
  add: 'Add an envelope',
  adding: 'Adding…',
  remove: 'Remove',
  markDelivered: 'Handed over',
  markUndelivered: 'Not handed over yet',
  handed: '{n} of {of} handed over',
};

export const vehiclesCopyEn: VehiclesCopy = {
  title: 'Cars and rides',
  sub: 'Getting from wherever you are getting ready to the hall and back: who drives, how many seats, who rides with whom.',
  empty: 'No cars yet. Add the first one and give it a name everybody will recognise.',
  name: 'Car',
  namePh: 'Car 1, Dad\'s car',
  driver: 'Driver',
  driverPh: 'Who is driving',
  phone: 'Phone',
  seats: 'seats',
  seatsTotal: 'seats in all',
  leg: 'Direction',
  legTo: 'To the hall',
  legFrom: 'Back',
  legBoth: 'Both ways',
  riders: 'Riding',
  ridersPh: 'Grandma, Aunt Rachel, the two kids',
  note: 'Note',
  notePh: 'Leaving home at 16:30',
  add: 'Add a car',
  adding: 'Adding…',
  remove: 'Remove',
};

export const meetingTemplatesCopyEn: MeetingTemplatesCopy = {
  title: 'Meeting templates',
  sub: 'The questions you ask at every meeting, in the order they come up. Each template is a button on every event file.',
  builtIn: 'The standing meetings',
  builtInHint: 'Built in and not editable. Copy one and change the copy.',
  copy: 'Copy to edit',
  copying: 'Copying',
  own: 'Your templates',
  none: 'No templates yet. Start from the first call, or from a blank page.',
  add: 'New template',
  name: 'Template name',
  namePh: 'First phone call',
  when: 'When it happens',
  whenPh: 'Before signing, a month before',
  blurb: 'A line about the meeting',
  blurbPh: 'What the meeting is for, in your words',
  sections: 'Sections',
  sectionTitle: 'Section title',
  sectionTitlePh: 'Who you are, the event, money',
  addSection: 'Another section',
  removeSection: 'Remove section',
  question: 'Question',
  questionPh: 'Roughly how many guests',
  kind: 'Answer type',
  kinds: {
    text: 'Short text', long: 'Long text', number: 'Number',
    time: 'Time', choice: 'Pick from a list', yesno: 'Yes or no',
  },
  options: 'Options',
  optionsPh: 'One per line',
  hint: 'Hint',
  hintPh: 'Shown in grey inside the field',
  addQuestion: 'Another question',
  removeQuestion: 'Remove question',
  moveUp: 'Move up',
  moveDown: 'Move down',
  questionsCount: 'Questions: {n}',
  archived: 'Archived',
  save: 'Save',
  saving: 'Saving',
  cancel: 'Cancel',
  remove: 'Delete',
  removeAsk: 'Delete this template? Meetings already written from it are kept.',
  saveFailed: 'Could not save',
  noQuestions: 'At least one question is needed',
};

export const timelineCopyEn: TimelineCopy = {
  title: 'The year\'s timeline',
  sub: 'A working plan from today to the event, in our rhythm: what closes when, and why then. Adjusted to the guest count and the location, with a reminder on every step, and added to the tasks in one press.',
  open: 'Build the year\'s timeline',
  close: 'Close',
  noDate: 'The event has no date yet. The plan is laid backwards from the date, so set it in the event details first.',
  guests: 'Estimated guest count',
  abroad: 'A wedding abroad, or most guests fly in',
  abroadHint: 'Invitations go out nine months ahead, and hotel rooms, a travel guide and passports are added.',
  ownersTitle: 'Who handles each area',
  ownerDefault: 'As in the plan',
  ownerProducer: 'Me',
  ownerClient: 'The couple',
  categories: {
    vendors: 'Venue and suppliers',
    guests: 'Guests and invitations',
    attire: 'Attire and beauty',
    money: 'Budget and payments',
    travel: 'Travel and transport',
    ceremony: 'Ceremony and the evening',
    legal: 'Registration and admin',
  },
  runway: { one: 'One day to the event', many: '{n} days to the event' },
  stepsCount: { one: 'One step', many: '{n} steps' },
  colTask: 'What',
  colDate: 'By when',
  colCategory: 'Area',
  colOwner: 'Who',
  colRemind: 'Reminder',
  colNote: 'Why then',
  remind: { one: 'A day before', many: '{n} days before' },
  atRisk: 'At risk',
  atRiskTitle: 'Already late',
  atRiskSub: 'Steps that should have closed by now. Laid over the next two weeks, in the right order, rather than dated in the past.',
  warnShort: 'Under nine months left. The plan is compressed, and the marked steps need attention this week.',
  warnAbroad: 'A wedding abroad with under nine months: the invitations cannot go out in time. Send them now, and phone the guests in parallel.',
  underestimated: 'Three things that tend to slip',
  tips: [
    'A printed invitation takes four to six weeks from design to delivery. Start the conversation with the printer before the wording is final.',
    'An ordered dress arrives months later, and then there are three fittings. "Start looking" is a step with a date, not an idea.',
    'Marriage registration needs documents that take weeks to obtain. Open the file three months out, not three weeks.',
  ],
  basis: 'The order and the lead times are the production\'s own rhythm, from the system\'s first plan, adjusted for weddings abroad and large ones. A template, not a law: once the steps are in the tasks, every date can be moved.',
  add: { one: 'Add one step to the tasks', many: 'Add {n} steps to the tasks' },
  adding: 'Adding',
  added: { none: 'Everything was already there', many: '{n} steps added to the tasks, each with a date and a reminder' },
  skipped: { one: 'One step was already on the list', many: '{n} steps were already on the list' },
  failed: 'Could not add',
  calendarTitle: 'And from there to the calendar',
  calendarSub: 'Every dated task lands in the subscribed calendar with its reminder: yours from the calendar page, the couple\'s from their own area, in Google, Apple and Outlook. When something moves here, it moves there.',
};

export const studioCopyEn: StudioCopy = {
  eyebrow: 'Design',
  title: 'The wedding\'s brand',
  sub: 'The board is read once: five colours with a role each, a pair of typefaces, three words, the motifs that repeat and one voice. Every printed piece and the guests\' site are built from it, in the same world.',
  subClient: 'What came out of the photographs you collected: the colours, the type, the words. Every printed piece comes in two options, and you choose.',
  none: 'No brand has been read from the board yet. When there is one, it appears here with all the pieces.',
  inputs: {
    title: 'Before the reading',
    words: 'Three words for the vibe',
    wordsPh: 'modern, garden, soft',
    reference: 'A brand or designer whose visual world you love',
    referencePh: 'Aesop, Le Labo, Glossier',
    colorsIn: 'Colours that must be in',
    colorsInPh: 'deep green, ivory',
    colorsOut: 'Colours that are out',
    colorsOutPh: 'baby pink',
    pinterest: 'A Pinterest board cannot be opened from here: Pinterest blocks reading boards. Save 8 to 15 pins as images and upload them to the inspiration board above. That is what gets read.',
  },
  read: 'Read the board',
  reading: 'Reading the photographs',
  readNone: 'The inspiration board has no photographs yet. The reading works on 8 to 15; fewer than 4 gives a thin result.',
  readFew: 'The board has {n} photographs. It can be read, but from 8 up the reading is more accurate.',
  readNoKey: 'Reading photographs needs the assistant\'s key on the server. Until then, extract colours in the browser and fill in the rest by hand.',
  readFail: 'The reading did not work. Try again, or extract colours in the browser.',
  extract: 'Extract colours from the photographs',
  extracting: 'Extracting',
  extractFail: 'The browser could not read the pixels of the photographs. Try again, or type the colours.',
  sheet: {
    title: 'Brand sheet',
    sub: 'The document everything else is built from. Any field can be corrected by hand.',
    palette: 'Palette',
    roles: { primary: 'Primary', secondary: 'Secondary', accent: 'Accent', light: 'Paper', dark: 'Ink' },
    fonts: 'Typefaces',
    fontsHint: 'Every pairing here sets Hebrew. The first for the names and headings, the second for everything else.',
    fontFor: 'Names',
    fontBody: 'Text',
    words: 'The three words',
    motifs: 'Motifs that repeat',
    voice: 'The voice',
    voicePh: 'Two sentences on how this brand speaks.',
    direction: 'The direction chosen, and why',
    lean: 'The board leans to',
    leanSafe: 'the quiet option',
    leanBold: 'the bold option',
    save: 'Save the brand sheet',
    saving: 'Saving',
    saved: 'Saved',
    byAi: 'read from the board',
    byHand: 'typed by hand',
    swatchName: 'Name',
  },
  texts: {
    title: 'The pieces\' texts',
    sub: 'A few lines the pieces need that the system does not have. Blank prints blank.',
    story: 'Our story',
    storyPh: 'How you met, in four lines.',
    travel: 'Getting there and staying',
    travelPh: 'Parking, shuttles, a recommended hotel.',
    registry: 'Gifts',
    registryPh: 'Through the site, or an envelope at the entrance.',
    menu: 'Menu',
    menuPh: 'One course per line',
  },
  pieces: {
    title: 'The pieces',
    sub: 'Every piece in two options side by side: quiet and bold. The marked one is the one that prints. The data comes from the event: the names, the date, the venue, the tables and the schedule.',
    names: {
      savedate: 'Save the date',
      invite: 'Invitation',
      rsvp: 'RSVP card',
      details: 'Details card',
      menu: 'Menu',
      table: 'Table numbers',
      welcome: 'Welcome sign',
      program: 'Program',
      website: 'Guests\' site',
    },
    safe: 'Quiet',
    bold: 'Bold',
    fits: 'fits the board better',
    pick: 'Choose',
    picked: 'Chosen',
    front: 'Front',
    back: 'Back',
    print: 'Print file',
    printHint: 'Opens a sheet with 3 mm bleed and crop marks. Save as PDF from the print dialog.',
    siteNote: 'The guests\' site takes the brand by itself: the same colours and typefaces on the page everyone opens from the link.',
    openSite: 'Open the guests\' site',
    tablesNone: 'No tables in the seating plan yet. The card is shown for table 1.',
    sizes: 'Sizes: invitation and save the date 5×7 in, RSVP 3.5×5, details, menu and program 4×9, tables 5×7, sign 18×24.',
  },
  on: {
    invite: 'We would be delighted to celebrate with you',
    savedate: 'Save the date',
    savedateBack: 'Invitation to follow',
    at: 'at',
    reception: 'Reception',
    rsvpTitle: 'RSVP',
    rsvpBy: 'Kindly reply by',
    rsvpHow: 'Reply at the link, or by phone',
    rsvpSite: 'Guests\' site',
    detailsTitle: 'Details',
    arrive: 'Getting there',
    stay: 'Staying and parking',
    menuTitle: 'Menu',
    table: 'Table',
    welcome: 'Welcome',
    welcomeTo: 'to the wedding of',
    program: 'Order of the evening',
    story: 'Our story',
    schedule: 'Schedule',
    travel: 'Travel',
    rsvp: 'RSVP',
    registry: 'Registry',
    days: 'days',
    dateTbd: 'Date to be set',
    defaultMoments: ['Reception', 'Ceremony', 'Dinner', 'Dancing'],
    defaultMenu: ['Starters', 'Mains', 'Dessert'],
  },
  printers: {
    title: 'Where to print',
    sub: 'Three levels of finish, from the dearest to the cheapest. The files from here suit all of them: 3 mm bleed, crop marks, standard sizes.',
    list: [
      { name: 'Moo', level: 'High finish', note: 'Thick stock, foil, painted edges. When the invitation is an object.' },
      { name: 'Minted', level: 'Design-led', note: 'Good quality and matching envelopes. Ships to Israel, long delivery.' },
      { name: 'Vistaprint', level: 'Budget', note: 'Cheap and fast. Enough for table cards and the sign, less so for the invitation.' },
    ],
    local: 'In Israel: any digital print shop takes these files as they are. Ask for 300 gsm or heavier and point at the crop marks.',
  },
  printPage: {
    back: 'Back to the pieces',
    print: 'Print or save as PDF',
    note: 'The sheet carries 3 mm bleed on every side and crop marks in the corners. In the print dialog: paper size as the page, margins 0, scale 100%.',
    tables: 'One page per table',
  },
};

export const journalEn: JournalCopy = {
  eyebrow: 'Research',
  title: 'Guest journal',
  sub: 'In the year before your own wedding you will go to four. Every one of them teaches something, and nobody remembers it when the time comes. Write down what worked, what to avoid, and what it means for your evening.',
  subProducer: 'What the couple wrote down at weddings they attended as guests. This is where you learn what they like before anyone argues about it.',
  open: 'Open the journal',
  back: 'Back to our area',
  add: 'Add a wedding',
  adding: 'Saving',
  cancel: 'Cancel',
  remove: 'Delete',
  none: 'No weddings written down yet. After the next one you go to, three lines here are worth more than any Pinterest board.',
  noneProducer: 'The couple has not written down any weddings yet.',
  form: {
    venue: 'Where it was',
    venuePh: 'The venue',
    date: 'When',
    style: 'Kind of event',
    styles: { garden: 'Garden', hall: 'Hall', fridayNoon: 'Friday afternoon', nature: 'Outdoors' },
    pros: 'What worked beautifully',
    prosNote: 'And in your own words',
    prosPh: 'What you want to remember',
    cons: 'What worked less well, and what to avoid',
    consNote: 'And in your own words',
    consPh: 'What you would not want at yours',
    takeaways: 'Takeaways for our wedding',
    takeawaysPh: 'One takeaway per line',
    takeawaysHint: 'Each line counts on its own, and appears in the summary under every area that wedding taught you about.',
    photos: 'Photographs from the venue',
    photosHint: 'Styling, a table, the lighting, anything worth showing a supplier. Several at once.',
    photosAdd: 'Add photographs',
    photosBusy: 'Uploading {n} of {m}',
    save: 'Save the wedding',
  },
  tags: {
    foodGood: 'The food was good',
    servedHot: 'Served hot',
    plentyFood: 'There was enough of it',
    barFast: 'The bar was quick',
    barGoodDrink: 'Good cocktails',
    soundRight: 'The sound was right',
    lightWarm: 'Warm lighting',
    receptionEasy: 'Reception stations easy to reach',
    seatingEnough: 'There was somewhere to sit',
    ranOnTime: 'It ran on time',
    ceremonyShort: 'A short, precise ceremony',
    staffPresent: 'Staff present all evening',
    parkingEasy: 'Easy parking',
    barQueue: 'A long queue at the bar',
    barRanOut: 'The drink ran out',
    foodCold: 'The food came cold',
    foodLate: 'The food came late',
    noVeganOption: 'Nothing for the vegans',
    musicTooLoud: 'Music too loud during dinner',
    lightHarsh: 'Harsh lighting',
    noSeating: 'Nowhere to sit at the reception',
    receptionCrowded: 'The reception was crowded',
    startedLate: 'It started late',
    longGaps: 'Long gaps between parts',
    noOneInCharge: 'Nobody to turn to',
    parkingHard: 'Parking was a nightmare',
  },
  summary: {
    title: 'What we learned, by area',
    sub: 'Everything collected, sorted by the part of your own evening it touches. Open the area on the day you book it.',
    areas: { catering: 'Catering', bar: 'Bar', design: 'Design and mood', timing: 'Timing', other: 'General' },
    worked: 'Worked',
    avoid: 'Avoid',
    ours: 'Our takeaways',
    times: 'at {n} weddings',
    none: 'The summary builds itself after the first wedding you write down.',
  },
  card: { at: 'at', noDate: 'no date', photos: 'photographs' },
};

export const circleEn: CircleCopy = {
  eyebrow: 'Community',
  title: 'Couples circle',
  sub: 'The couples of one producer, in one place. Ask, answer, and recommend suppliers to the people who are exactly there. Post by name or anonymously.',
  subProducer: 'Your couples\' circle. Your answer is marked as the producer\'s, so it is clear who said it.',
  open: 'Open the circle',
  back: 'Back to our area',
  categories: { general: 'Questions and doubts', vendors: 'Supplier recommendations', styling: 'Styling, dresses and suits', food: 'Bar, drink and menus' },
  all: 'All',
  ask: 'Ask the circle',
  asking: 'Posting',
  cancel: 'Cancel',
  form: {
    category: 'Which topic',
    title: 'The heading',
    titlePh: 'One question, in a sentence',
    content: 'And what you wanted to ask',
    contentPh: 'The more detail you give, the more useful the answers',
    anonymous: 'Post anonymously',
    anonymousHint: 'Your name is not shown. In its place, "engaged couple", with how many months you have left.',
    post: 'Post',
  },
  reply: {
    placeholder: 'Answer this couple',
    post: 'Send the answer',
    posting: 'Sending',
    none: 'No answers yet. If you know something, this is the moment.',
    count: { one: 'One answer', many: '{n} answers' },
  },
  producerBadge: 'The producer',
  anon: { one: 'Engaged couple (one month to go)', many: 'Engaged couple ({n} months to go)', plain: 'Engaged couple' },
  upvote: 'This helped',
  upvoted: 'You marked this as helpful',
  upvotes: { one: 'One person found this helpful', many: '{n} found this helpful' },
  mine: 'Yours',
  remove: 'Delete',
  none: 'No posts in the circle yet. The first question is usually the one everybody wanted to ask.',
  noneCategory: 'No posts on this topic yet.',
  closed: 'The circle is opened by the producer. If it is not open to you, it is worth asking them.',
  rules: 'This is a place for couples planning with the same producer. A supplier\'s name, a price you were quoted, what worked and what did not: all fine. What is not fine is a private person\'s name.',
};
