import type {
  PortalCopy, FilesCopy, SheetsCopy, TasksCopy, MoneyCopy, BoardCopy,
  GuestsCopy, SeatingCopy, DayCopy, ThreadCopy, PartyCopy, ContractCopy, EventFileCopy,
} from './appUi.ts';

/**
 * The couple's own area, in English.
 *
 * Only what a couple sees. The producer's screens stay Hebrew: there is one
 * producer, he works in Hebrew, and translating the admin would be work nobody
 * reads. Where a block is shared between the two sides, only the sentences
 * addressed to the couple were written with them in mind; the producer's
 * variant of the same key is translated too, because the type demands the
 * whole block and a half translated object is worse than none.
 *
 * Same guarantee as the public site: every type here is the Hebrew block put
 * through `Wide<>`, so the keys, the nesting and the tuple lengths have to
 * match exactly and only the words are free.
 */

export const portalEn: PortalCopy = {
  title: 'Our area',
  guestSite: {
    title: 'The link for your guests',
    sub: 'Send it on WhatsApp to everyone invited. Each guest finds themselves by phone number and replies.',
    copy: 'Copy the link',
    copied: 'Copied',
    open: 'Open the page',
    share: 'Share on WhatsApp',
    shareText: 'You are invited to celebrate with us! All the details and the RSVP are here:',
  },
  sub: 'Everything about your event, in one place.',
  empty: 'No event has been linked to you yet. The production will open it and you will hear from us.',
  emptyWho: 'You are signed in as {email}.',
  emptyMismatch:
    'If the invitation went to a different address, that is why this screen is empty. You can sign out '
    + 'and sign in with the address the invitation arrived at, or simply write to us and we will '
    + 'attach this address to the event.',
  daysLeft: 'days to the wedding',
  dateTbd: 'The date is not set yet',
  summary: 'A quick look',
  rowBudget: 'Budget',
  rowRsvp: 'Replies',
  rowBoard: 'Inspiration',
  rowVendors: 'Suppliers',
};

export const filesEn: FilesCopy = {
  title: 'Files and photographs',
  subClient: 'Everything you wanted to send us and had nowhere to put. Photographs, the invitation, a list, a plan from the venue.',
  subProducer: 'The shared folder for this event. What the couple uploaded and what you uploaded for them.',
  add: 'Add files',
  adding: 'Uploading',
  drop: 'Drag them here, or choose from your device',
  dropHint: 'Up to 50MB a file. Images, PDF, Word, Excel, video and audio.',
  none: 'Nothing here yet.',
  noneProducer: 'No files have been uploaded to this event yet.',
  open: 'Open',
  download: 'Download',
  remove: 'Remove',
  note: 'Note',
  notePh: 'What this file is',
  noteSave: 'Save',
  by: 'Uploaded by',
  photos: 'Photographs',
  documents: 'Documents',
  tooBig: 'That file is too large. Up to 50MB.',
  badType: 'That file type is not supported',
  failed: 'The upload failed. Please try again.',

  media: {
    title: 'Photographs',
    sub: 'The venue, the design, the inspiration and the suppliers. Every picture carries a tag, so it can still be found after the sixtieth.',
    tagForUpload: 'Tag for the pictures you are adding now',
    all: 'All',
    untagged: 'Untagged',
    tags: {
      venue: 'Venue',
      design: 'Design',
      inspiration: 'Inspiration',
      vendors: 'Suppliers',
    },
    count: '{n} photographs',
    one: 'One photograph',
    none: 'No photographs under this tag yet.',
    open: 'Enlarge',
    close: 'Close',
    prev: 'Previous',
    next: 'Next',
    retag: 'Change tag',
    manage: 'Manage',
    done: 'Done',
  },
};

export const sheetsEn: SheetsCopy = {
  close: 'Close',
  contact: {
    open: 'Talk to the producer',
    title: 'Your producer',
    sub: 'Available Sunday to Thursday, 09:00 to 19:00',
    call: 'Phone call',
    whatsapp: 'WhatsApp message',
    whatsappMeta: 'Answered within the hour',
    meeting: 'Book a meeting',
    meetingMeta: 'Open slots in the diary',
  },
  report: {
    open: 'Report a problem',
    title: 'Report a problem',
    sub: 'The report goes straight to the production desk and is recorded on the event.',
    topics: ['Timing and schedule', 'A supplier is not answering', 'Payment', 'Replies', 'Something broken in the app', 'Something else'],
    placeholder: 'What happened? Add any detail you have',
    submit: 'Send the report',
    sending: 'Sending…',
    sent: 'The report reached the desk',
    failed: 'We could not send it. Please try again.',
    empty: 'Please write what happened',
  },
};

export const tasksEn: TasksCopy = {
  reorder: 'Drag to reorder',
  title: 'Tasks',
  subProducer: 'A shared list. Both sides see it and either side can tick something off.',
  subClient: 'What is left to do, and what is already settled.',
  add: 'Add a task',
  adding: 'Adding',
  titlePh: 'What needs doing',
  due: 'By when',
  owner: 'Whose',
  ownerProducer: 'Ours',
  ownerClient: 'Yours',
  ownerProducerClientView: 'Production',
  ownerClientClientView: 'Ours',
  none: 'No tasks yet.',
  open: 'Open',
  done: 'Done',
  overdue: 'Overdue',
  noDue: 'No date',
  remove: 'Delete',
  byProducer: 'Written by the production',
  byClient: 'Written by the couple',
};

export const moneyEn: MoneyCopy = {
  payTitle: 'Payments',
  paySubProducer: 'What the couple has paid and what is still open. They see this, and only you mark something paid.',
  paySubClient: 'What has been paid and what is still open.',
  payWhat: 'What for',
  payWhatPh: 'Deposit',
  payAmount: 'Amount',
  payDue: 'Due by',
  payAdd: 'Add a payment',
  payAdding: 'Adding',
  payNone: 'No payments recorded yet.',
  paid: 'Paid',
  unpaid: 'Open',
  overdue: 'Overdue',
  totalPaid: 'Paid',
  totalOwed: 'Still to pay',
  totalAll: 'Total',
  markPaid: 'Mark as paid',
  markUnpaid: 'Undo that mark',
  remove: 'Delete',
  noDue: 'No date',

  budTitle: 'Budget',
  budSub: 'The estimate against what was actually agreed, item by item.',
  budLabel: 'Item',
  budLabelPh: 'Catering',
  budCategory: 'Category',
  budVendor: 'Supplier',
  budEstimate: 'Estimate',
  budAgreed: 'Agreed',
  budAdd: 'Add an item',
  scan: 'Photograph a receipt',
  scanning: 'Reading the receipt',
  scanHint: 'Photograph a supplier receipt and the fields fill themselves. Nothing is saved until you press add.',
  scanFilled: 'Filled in from the receipt. Check it and add it.',
  scanUnsure: 'I filled in what I could read, but not all of it was clear. Worth checking the amount.',
  scanFailed: 'I could not read the image. You can fill it in by hand.',
  scanTooBig: 'That image is too large. Try photographing it again.',
  budNone: 'No budget items recorded yet.',
  budTotalEst: 'Total estimate',
  budTotalAgreed: 'Total agreed',
  budDiff: 'Difference',
  budUnder: 'under the estimate',
  budOver: 'over the estimate',
  budShow: 'The couple sees the budget',
  budHidden: 'Hidden from the couple',
  budVisible: 'Visible to the couple',
  budHiddenNote: 'The budget is hidden from the couple. You can open it to them at any point.',
};

export const boardEn: BoardCopy = {
  eyebrow: 'Inspiration',
  title: 'Inspiration board',
  subClient: 'The photographs that made you say "that is the one". Everything collected here goes to the suppliers with us.',
  subProducer: 'The photographs the couple collected. Read only, they manage the board from their own area.',
  upload: 'Upload a photograph',
  choose: 'Choose a photograph',
  uploading: 'Uploading',
  caption: 'Caption',
  captionPh: 'What you liked here',
  category: 'Category',
  all: 'All',
  none: 'Nothing on the board yet.',
  noneProducer: 'The couple has not uploaded anything yet.',
  remove: 'Remove',
  tooBig: 'That image is too large. Up to 8MB.',
};

export const guestsEn: GuestsCopy = {
  title: 'Replies',
  sub: 'The guest list and their answers. Every guest gets a personal link.',
  attending: 'Coming',
  declined: 'Not coming',
  pending: 'No answer yet',
  invited: 'Invited',
  heads: 'Total people',
  showOnly: 'Show in the list',
  addTitle: 'Add guests',
  addHint: 'One name a line. "Name, side, phone" works too.',
  addPh: 'The Cohen family, bride, 0501234567\nDavid and Ronit\nYael from work',
  side: 'Side (default)',
  add: 'Add to the list',
  adding: 'Adding',
  none: 'No guests added yet.',
  copyLink: 'Copy the link',
  copied: 'Copied',
  remove: 'Remove',
  markAttending: 'Mark coming',
  markDeclined: 'Mark not coming',
  markPending: 'Reset',
  guest: 'Guest',
  status: 'Answer',
  party: 'People',
  dietCol: 'Food',
  noteCol: 'Note',
};

export const seatingEn: SeatingCopy = {
  dragHint: 'Drag a guest onto a table, or use the picker. A table with no room will not take the drop.',
  title: 'Seating',
  sub: 'Only people who replied get a seat. A table will not seat more people than it has chairs.',
  addTable: 'New table',
  tableName: 'Name',
  tableNamePh: 'Table 1',
  seats: 'Seats',
  add: 'Add',
  adding: 'Adding',
  noTables: 'No tables added yet.',
  seated: 'Seated',
  free: 'Free',
  full: 'Full',
  emptyTable: 'Nobody at this table yet.',
  unseated: 'Waiting to be seated',
  unseatedNone: 'Everybody who replied has a seat. 🎉',
  place: 'Seat at',
  choose: 'Choose a table',
  unseat: 'Take off the table',
  removeTable: 'Delete the table',
  removeTableHint: 'The guests are not deleted, they go back to the waiting list.',
  peopleShort: 'people',
  needRsvp: 'Nobody has replied yet. Seat people once the answers start coming in.',
  floor: 'Floor plan',
  floorSub: 'Every circle is a table and every dot around it is a chair. A taken chair is marked in gold.',
  openTable: 'Open the table',
  seatFree: 'Free chair',
};

export const dayEn: DayCopy = {
  moveUp: 'Move earlier',
  moveDown: 'Move later',
  dragHint: 'You can also drag a row up or down',
  audience: 'Who this schedule is for (empty = everybody):',
  title: 'The day itself',
  sub: 'The morning looks different for each of you, so each of you has their own track, and what is shared sits in the middle.',
  shared: 'Shared',
  addTitle: 'What happens',
  addTitlePh: 'Hair and makeup',
  time: 'Time',
  note: 'Note',
  notePh: 'Where, with whom',
  track: 'Track',
  add: 'Add to the schedule',
  adding: 'Adding',
  none: 'No schedule built for the day yet.',
  emptyTrack: 'Nothing on this track yet.',
  remove: 'Delete',
  rename: 'Rename the tracks',
  renameSave: 'Save the names',
  renameHint: 'What you call the two tracks. These names are yours.',

  owner: 'Who is responsible',
  ownerPh: 'Name',
  duration: 'How long',
  durationPh: 'min',
  untilNext: 'until the next',
  edit: 'Edit',
  save: 'Save',
  cancel: 'Cancel',
  addOpen: 'Add a row',
  addClose: 'Close',
  overlap: 'Overlaps "{title}" on the same track',
  crossesMidnight: 'The schedule runs past midnight, and the rows are ordered by the evening rather than by the clock.',
  totalLines: '{n} rows',
  span: '{from} to {to}',

  templateTitle: 'Start from a ready schedule',
  templateSub: 'Pick a starting point, then delete and change whatever does not fit. Only available while the schedule is empty.',
  templateApply: 'Open the schedule',
  templateApplying: 'Opening',
  templateOr: 'or start from an empty row',
  keyMoment: 'Key moment',
  keyMomentHint: 'The desk will warn 10 minutes before',
};

export const threadEn: ThreadCopy = {
  title: 'Messages',
  sub: 'Everything agreed about the event, in one place that stays with it.',
  empty: 'No messages yet. Write the first one.',
  placeholder: 'Write a message',
  send: 'Send',
  sending: 'Sending',
  retract: 'Delete',
  today: 'Today',
  yesterday: 'Yesterday',
};

export const partyEn: PartyCopy = {
  name: 'Name of the other party',
  namePh: 'The supplier or the couple',
  role: 'Role',
  rolePh: 'DJ, photographer, officiant',
};

export const contractEn: ContractCopy = {
  title: 'Agreements',
  subProducer: 'A draft stays with you. Once it is sent the couple sees it, and once it is signed the terms stop moving.',
  subClient: 'What was agreed, written down. Signing here carries the same weight as signing on paper.',
  newContract: 'New agreement',
  cancel: 'Cancel',
  untitled: 'Untitled agreement',
  titleLabel: 'Name of the agreement',
  titlePh: 'Wedding production agreement',
  amountLabel: 'Amount',
  amountPh: 'Amount in shekels',
  bodyLabel: 'Terms',
  bodyPh: 'The fee, the payment schedule, what is included and what is not, cancellation terms.',
  attach: 'Attach a document',
  attached: 'The document is attached',
  uploading: 'Uploading',
  tooBig: 'That file is too large. Up to 20MB.',
  uploadFailed: 'The upload failed. Please try again.',
  saveDraft: 'Save the draft',
  saving: 'Saving',
  draftHint: 'The couple cannot see the draft until you send it.',
  send: 'Send for signature',
  discard: 'Delete',
  void: 'Void the agreement',
  openDoc: 'Open the attached document',
  signedBy: 'Signed by',
  signIntro: 'Read the terms? Sign with your full name to confirm.',
  signNameLabel: 'Full name for the signature',
  signNamePh: 'Full name',
  sign: 'Sign',
  signing: 'Signing',
  signLegal: 'The signature is recorded with the name, the date and the time, and with a fingerprint of the text that was signed. Once signed, the terms cannot be changed.',
  tampered: 'The text shown here is not the text that was signed. Do not rely on it, contact the producer.',
  emptyProducer: 'No agreement has been created for this event yet.',
  emptyClient: 'No agreement has been sent to you yet.',
  status: {
    draft: 'Draft',
    sent: 'Waiting for signature',
    signed: 'Signed',
    void: 'Void',
  },
};

export const eventFileEn: EventFileCopy = {
  music: {
    title: 'Music',
    sub: 'Seven moments that need a song. The list goes to the DJ exactly as it is.',
    song: 'Song',
    songPh: 'Name of the song',
    artist: 'Artist',
    note: 'Note',
    notePh: 'Which version, how long, where to stop',
    save: 'Save',
    chosen: '{n} of {of} chosen',
    empty: 'No song chosen for any moment yet.',
  },

  equipment: {
    title: 'Equipment',
    sub: 'What is needed, and what is already settled.',
    undecided: 'Not looked at yet',
    off: 'Not needed',
    needed: 'Needed',
    sorted: 'Settled',
    openCountOne: 'One item open',
    openCountMany: '{n} items open',
    allSorted: 'All settled.',
  },

  couple: {
    title: 'Personal details',
    sub: 'What makes a wedding theirs. The couple fills it in and you see it.',
    personA: 'One of you',
    personB: 'The other',
    name: 'Name',
    namePh: 'What they are called',
    save: 'Save',
    saved: 'Saved',
    emptyHint: 'Empty. You can fill it in here, or ask the couple to fill it in from their own area.',
  },
};
