import type {
  ConsoleCopy, LeadCopy, CrewCopy, VendorCopy, TemplateCopy, BarCopy, UpdateCopy, LinkCopy,
  SignCopy, SiteEditorCopy, HebrewCalCopy, LabelCopy, KnowledgeCopy, JumpCopy, CopilotCopy,
  ArchiveCopy, MeetingCopy, NoteCopy, WorkflowCopy, ReferralCopy,
} from './appUi.ts';

/**
 * The producer's console, in English.
 *
 * The couple's area went first and the console stayed Hebrew on the theory
 * that there was one producer and he worked in Hebrew. There is now a switch
 * on the console's own shell, and a producer who presses it should get a
 * console, not a layout flipped left-to-right with every word still in
 * Hebrew. Every block here is its Hebrew twin put through `Wide<>`, so the
 * keys, the nesting and the tuple lengths have to match and only the words
 * are free; and none of it is a function, because all of it crosses the
 * client boundary.
 *
 * What is deliberately not here: the playbook, the operating book, the
 * standing checklist's task titles and the five meeting questionnaires. Those
 * are documents rather than chrome, and a translated document is a second
 * document to keep true.
 */

export const consoleEn: ConsoleCopy = {
  signOut: 'Sign out',
  overview2: {
    clear: 'All handled',
    clearSub: 'Nothing is waiting on a decision from you right now.',
    begin: {
      eyebrow: 'Start here',
      sub: 'There are no events in the system yet, so this is the right order to begin in.',
      cta: 'To the branding screen',
      book: 'The full operating book',
    },
    needsYou: 'Waiting on you',
    now: 'Urgent',
    soon: 'This week',
    nextEvent: 'Next event',
    inDays: { today: 'Today', tomorrow: 'Tomorrow', later: 'In {n} days' },
    money: 'Money',
    paid: 'Paid',
    owed: 'Open',
    overdue: 'Overdue',
    allClients: 'All events',
    seeAll: 'Show all',
  },

  profile: {
    title: 'My profile',
    sub: 'The name and picture everyone working with you on an event sees.',
    name: 'Full name',
    picture: 'Profile picture',
    choose: 'Choose a picture',
    replace: 'Replace picture',
    remove: 'Remove picture',
    hint: 'JPG, PNG or WEBP · up to 5MB',
    saving: 'Saving…',
    save: 'Save',
    saved: 'Saved',
    tooBig: 'That file is over 5MB. Choose a smaller picture.',
    notImage: 'Only an image can be uploaded.',
    uploadFailed: 'The upload failed. Try again.',
  },

  insights: {
    conversion: {
      title: 'What came of the enquiries',
      sub: 'Counted by events actually opened, not by a status set by hand.',
      rate: 'Became an event',
      count: 'of {n} enquiries',
      wait: 'Time to close',
      days: '{n} days',
      none: 'Not enough enquiries yet to say anything.',
    },
    title: 'Insights',
    sub: 'Where the business really stands, not how it feels.',
    empty: 'Not enough data yet to show anything real. After a few leads and events this screen fills itself in.',
    thin: 'Too little data',
    thinHint: 'Percentages are shown from five cases up. Until then the number itself is shown.',
    ofPrev: 'of the previous step',

    funnel: {
      title: 'From enquiry to contract',
      sub: 'Each step is counted together with what follows it, so the screen never shows more signatures than calls.',
      leads: 'Enquiries',
      contacted: 'Answered',
      meeting: 'Meeting',
      won: 'Closed',
    },

    sources: {
      title: 'Where the work comes from',
      sub: 'A channel with one closed enquiry is one enquiry, not a hundred percent.',
      source: 'Channel',
      leads: 'Enquiries',
      won: 'Closed',
      rate: 'Close rate',
      unknown: 'Unknown',
    },

    response: {
      title: 'How long an enquiry waits',
      sub: 'The median, not the average. One enquiry forgotten for two weeks should not colour the whole month.',
      median: 'Median response time',
      answered: 'Enquiries answered',
      waiting: 'Waiting for a reply',
      hours: { lessThanOne: 'Under an hour', one: 'An hour', many: '{n} hours' },
      none: 'Not enough answered enquiries yet',
    },

    cash: {
      title: 'Money',
      sub: 'Three numbers, not one. What came in, what is still due, and what was due and has not arrived.',
      collected: 'Collected',
      due: 'Open',
      overdue: 'Overdue',
      overdueCount: { one: 'One payment', many: '{n} payments' },
    },

    health: {
      title: 'What needs attention',
      signed: 'Events with a signed contract',
      overdueTasks: 'Overdue tasks',
      waiting: 'Enquiries nobody has answered yet',
      clear: 'No bottlenecks right now.',
      toLeads: 'To the leads screen',
      toClients: 'To the events',
    },
  },

  dayOf: {
    awake: 'The screen stays on for as long as this page is open.',
    title: 'Event control room',
    sub: 'What is happening now, what is next, and who should be here.',
    open: 'Open the control room',
    notToday: 'The event is not today, so there is no running clock here. The schedule is shown as it was written.',
    empty: 'No schedule for this event yet. You can build it on the event screen.',
    toEvent: 'To the event screen',
    now: 'Now',
    next: 'Up next',
    nothingNow: 'Nothing is scheduled right now',
    nothingNext: 'That was the last thing on the schedule',
    done: 'Done',
    late: 'Overdue',
    tick: 'Mark as done',
    untick: 'Undo',
    doneAt: 'Marked at {t}',
    saving: 'Saving',
    notSaved: 'Not saved. Try again.',
    schedule: 'Full schedule',
    openCount: { one: 'One line open', many: '{n} lines open' },

    people: {
      title: 'Who should be here',
      sub: 'Crew and suppliers in one list, by arrival time.',
      dueSoon: 'Due to arrive now',
      noTime: 'No time',
      call: 'Call',
      whatsapp: 'WhatsApp',
      crew: 'Crew',
      vendor: 'Supplier',
      empty: 'Nobody has been added to this event yet.',
      here: 'Arrived',
      arrived: 'Here',
      arrivedAt: 'Arrived at {t}',
      undo: 'Undo',
      notSaved: 'Not saved. Try again.',
      missing: 'Not here yet',
      headcount: '{here} of {of} here',
    },

    alert: {
      inMinutes: { now: 'Starting now', one: 'In a minute', many: 'In {n} minutes' },
      dismiss: 'Got it',
    },

    keyMoment: 'Key moment',

    broadcast: {
      title: 'Message everyone',
      sub: 'Opens WhatsApp to each person separately with the same message. Nothing is sent automatically: a message to a supplier mid-evening goes out by hand.',
      open: 'Urgent message',
      placeholder: 'What is happening and what to do',
      presets: [
        'Change to the schedule, please check with me before continuing.',
        'You are needed at the main entrance now.',
        'Fifteen minute delay, no need to rush.',
      ],
      send: 'Open WhatsApp',
      to: 'To',
      allHere: 'Everyone who is here',
      allMissing: 'Everyone not here yet',
      everyone: 'Everyone',
      noPhones: 'Nobody on the list has a phone number saved.',
      count: { one: 'One contact', many: '{n} contacts' },
      cancel: 'Close',
    },
  },

  brand: {
    title: 'My branding',
    sub: 'How your business looks to the couples who work with you. None of them ever sees the platform\'s name.',
    name: 'Business name',
    namePh: 'Keren Productions',
    tagline: 'Tagline',
    taglinePh: 'Boutique weddings in the north',
    logo: 'Logo',
    logoHint: 'PNG or SVG on a transparent background · up to 5MB',
    logoChoose: 'Choose a logo',
    logoReplace: 'Replace logo',
    logoRemove: 'Remove logo',

    assets: {
      title: 'Brand files',
      sub: 'The logo, the app icon and the cover picture. All three appear for your couples and nowhere else.',
      choose: 'Choose a file',
      replace: 'Replace',
      remove: 'Remove',
      uploading: 'Uploading',
      uploaded: 'Saved',
      empty: 'Not uploaded yet',
      tooBig: 'That file is too large.',
      badType: 'That file type does not belong here.',
      failed: 'The upload failed. Try again.',
      logo: {
        title: 'Logo',
        where: 'Appears at the top of the couples\' screen, in emails and on your sign-in page.',
        rules: ['PNG or SVG on a transparent background', 'At least 512 by 512 pixels', 'Square, or wide like a banner', 'Up to 2MB'],
      },
      icon: {
        title: 'App icon',
        where: 'The icon on the home screen when the app is installed on a phone.',
        rules: ['Square PNG, 512 by 512 pixels', 'No transparency and no empty margins', 'A simple shape that still reads at 60 pixels', 'Up to 1MB'],
      },
      cover: {
        title: 'Cover picture',
        where: 'The card WhatsApp draws for your link, and the background of the sign-in page.',
        rules: ['JPG or WebP', '1920 by 1080 pixels, 16:9', 'A real picture from an event, with no text on it', 'Up to 5MB'],
      },
    },
    accent: 'Accent colour',
    accentHint: 'The colours here were checked for readability against the background and the text. That is why it is a list and not a free colour picker.',
    whatsapp: 'WhatsApp',
    booking: 'Meeting booking link',
    address: 'Web address',
    slug: 'Your short name in the address',
    slugHint: 'Lower-case English letters, digits and hyphens only. No dots, no spaces, no Hebrew. For example: eden-haimov',
    slugPreview: 'The address you send couples will be:',
    slugBad: 'There is a character here that does not fit an address. You can use this version instead:',
    slugUse: 'Use it',
    slugShort: 'Too short. At least three characters.',
    domain: 'Your own domain (optional)',
    domainHint: 'Only for those who already own a domain they bought themselves. For most producers the short name above is enough. Connecting the DNS is a separate step.',
    shareTitle: 'Your link for couples',
    shareSub: 'Send this link, not the site\'s address. The card WhatsApp draws for it carries only your name and logo, and from there the couple enters their area.',
    shareNoSlug: 'Set a subdomain above and save, and the link appears here.',
    shareCopy: 'Copy',
    shareCopied: 'Copied',
    shareWhatsapp: 'Send on WhatsApp',
    shareText: 'Hello, here is the link to your personal area:',
    preview: 'Preview',
    save: 'Save',
    saving: 'Saving…',
    saved: 'Saved',
    failed: 'Could not save. Try again.',
    slugTaken: 'That subdomain is already taken.',
    slugShape: 'Lower-case English letters, digits and hyphens only.',
  },

  nav: {
    overview: 'Overview',
    leads: 'Leads',
    clients: 'Events',
    calendar: 'Calendar',
    insights: 'Insights',
    brand: 'Branding',
    vendors: 'Suppliers',
    store: 'Store',
    sop: 'Guides',
    knowledge: 'Knowledge',
    guide: 'Operating book',
    site: 'The site',
    admin: 'Administration',
    portal: 'Our area',
    more: 'More',
    moreTitle: 'More screens',
    close: 'Close',
  },
  pending: {
    title: 'Your account is awaiting approval',
    body: [
      'You signed up successfully, and the account opens once the administrator approves it.',
      'Until then there is no access to data and nothing to do here.',
      'The moment the account is approved, signing in works from this same address.',
    ],
    statusLabel: 'Status',
    statuses: {
      pending: 'Awaiting approval',
      approved: 'Approved',
      suspended: 'Suspended',
      rejected: 'Declined',
    },
  },
  overview: {
    greeting: 'Hello',
    leadsTitle: 'New leads',
    clientsTitle: 'Active events',
    tasksTitle: 'Open tasks',
    empty: 'Nothing to show here yet.',
  },
  leads: {
    title: 'Leads',
    sub: 'Every enquiry that came in from the site, in order of arrival.',
    empty: 'No enquiries yet.',
    cols: { name: 'Name', contact: 'Contact', event: 'Event', date: 'Date', guests: 'Guests', status: 'Status' },
    statuses: { new: 'New', contacted: 'Contacted', meeting: 'Meeting set', won: 'Closed', lost: 'Not relevant' },
  },
  clients: {
    title: 'Events',
    sub: 'Every couple or client with a workspace of their own.',
    empty: 'No events opened yet.',
    cols: { name: 'Name', date: 'Date', venue: 'Venue', guests: 'Guests' },
    noDate: 'Not set',
  },
  admin: {
    title: 'Administration',
    sub: 'Who is on the platform, who is working, and what is open to each kind of client.',
    waiting: 'Awaiting approval',
    producers: 'Producers',
    empty: 'No producer has signed up yet.',
    approve: 'Approve',
    reject: 'Decline',
    suspend: 'Suspend',
    restore: 'Restore',
    rootBadge: 'Platform owner',
    kind: {
      title: 'What this account is',
      sub: 'Everyone who signs up is set as a producer by default. This is where it is corrected.',
      producer: 'Producer',
      producerNote: 'A production business. Goes back to waiting, and approval grants access.',
      diy: 'A couple planning on their own',
      diyNote: 'A workspace of their own is opened, and they enter it straight away.',
      managed: 'A producer\'s couple',
      managedNote: 'Waiting for a producer to invite them to their event.',
      current: 'Currently',
      isProducer: 'Producer',
      isClient: 'Client',
    },
    oneLive: 'active event',
    manyLive: 'active events',
    ofTotal: 'of',
    never: 'Never signed in',
    lastSeen: 'Last signed in',
    statsFailed: 'Could not read the numbers right now.',

    privacy: {
      title: 'What this screen does not show',
      body: [
        'Other producers\' events, guests, budgets, contracts and messages are not reachable from here, nor through a direct query.',
        'That is enforced in the database and not in the screen\'s code, so there is no way around it.',
        'The price: you cannot peek at another producer\'s event to understand why something looks odd to them. Support happens over a shared screen.',
      ],
    },

    stats: {
      title: 'Snapshot',
      users: 'Users',
      active30: 'Active in 30 days',
      neverSeen: 'Signed up, never signed in',
      producers: 'Producers',
      approved: 'Approved',
      pending: 'Waiting',
      blocked: 'Suspended or declined',
      couples: 'Couples',
      managed: 'With a producer',
      diy: 'On their own',
      events: 'Events',
      live: 'Active',
      leads: 'Leads',
      last30: 'in 30 days',
    },

    board: {
      title: 'Who is working',
      sub: 'Numbers only. No couple\'s name and no event\'s name appear here.',
      events: 'Events',
      leads: 'Leads',
      signed: 'Signed contracts',
    },

    flags: {
      title: 'What is open to whom',
      sub: 'A couple on their own and a couple with a producer are not the same client. This is where what each gets is decided.',
      diy: 'On their own',
      managed: 'With a producer',
      on: 'Open',
      off: 'Closed',
      saved: 'Saved',
      note: 'Nothing is ever closed to the producer. The difference is in what the couple gets.',
    },
  },
  newClient: {
    title: 'New event',
    open: 'Open an event',
    sub: 'Open a workspace, then invite the couple into it.',
    name: 'Event name',
    namePh: 'Noa and Itai',
    kind: 'Kind of event',
    date: 'Date',
    venue: 'Venue',
    guests: 'Estimated guests',
    submit: 'Open the event',
    saving: 'Opening',
    cancel: 'Cancel',
  },
  live: {
    offline: 'No connection, this screen may be out of date',
  },

  guestImport: {
    open: 'Import a list from a file',
    export: 'Export to Excel',
    hint: 'A CSV file from Excel or Google Sheets. The headings can be in Hebrew or English: full name, side, phone, party size. A file with no headings works too.',
    orPaste: 'Or paste directly:',
    pastePh: 'Noa Cohen,bride,0501111111\nDanny Levi,groom,0502222222',
    import: 'Import',
    importing: 'Importing',
    added: 'Added',
    duplicates: 'Already on the list',
    nothingNew: 'Everyone was already on the list. Nobody was added.',
    skipped: 'Rows that could not be read',
    line: 'Row',
  },

  calendar: {
    title: 'Calendar',
    sub: 'The events, what has to happen before them, and when the money is due, on one line.',
    subscribe: 'Download a calendar file',
    empty: 'Nothing in the calendar ahead.',
    addEvent: 'Add the event to the calendar',
    grid: 'Month view',
    gridSub: 'Every event, task and payment on its day, for every couple. The day\'s tint is the Hebrew calendar: red for no weddings, amber for depends on custom.',
    more: 'and {n} more',
    legendEvent: 'Event',
    legendTask: 'Task',
    legendPayment: 'Payment',
    list: 'The list',

    feed: {
      title: 'A calendar that updates itself',
      sub: 'The file you download is a snapshot of today. A subscription updates by itself every time something moves.',
      create: 'Create a subscription link',
      creating: 'One moment…',
      open: 'Open in calendar',
      copy: 'Copy the address',
      copied: 'Copied',
      revoke: 'Revoke the link',
      revoked: 'The link was revoked. You can create a new one at any time.',
      warning: 'This address is the key. Anyone holding it sees the calendar, so do not share it.',
      how: 'On iPhone the link opens straight in the calendar. In Google Calendar, paste the address under Add calendar, From URL.',
    },

    legendEntry: 'My entry',
    day: {
      title: 'On this day',
      empty: 'Nothing on this day. Add something.',
      add: 'Add to the calendar',
      edit: 'Edit',
      close: 'Close',
      titleLabel: 'What',
      titlePh: 'Meeting with the florist',
      time: 'Time',
      allDay: 'All day',
      duration: 'Length',
      minutes: 'minutes',
      event: 'On an event',
      noEvent: 'Not on an event',
      note: 'Note',
      save: 'Save',
      saving: 'Saving',
      remove: 'Delete',
      cancel: 'Cancel',
      hint: 'Pressing a day on the grid opens it here. What is saved goes to the phone\'s calendar, and if Google is connected, there too within a moment.',
    },
    google: {
      title: 'Google Calendar',
      subOff: 'Two-way link: every event, task, payment and entry goes into a calendar of its own in your Google account, and what you move or add there on the phone comes back here. The sync runs every quarter hour.',
      subOn: 'Connected. A calendar named after the business was created in the Google account, and everything here appears there. What is added or moved there comes back here.',
      connect: 'Connect Google Calendar',
      connectedAs: 'Connected as',
      lastSync: 'Last sync',
      never: 'Not yet',
      syncNow: 'Sync now',
      disconnect: 'Disconnect',
      unconfigured: 'The Google link needs Google Cloud keys on the server. The set-google.sh script writes them.',
      error: 'The last sync failed',
      how: 'On the phone: Google Calendar, settings, make sure the calendar named after the business is ticked. Move an event there and the date moves here. A new entry there becomes an entry here.',
      moved: 'Connected. The calendar was created and everything here went into it.',
      denied: 'The connection was not approved at Google.',
      stale: 'The connection expired. Try again.',
      failed: 'Google returned no keys. Try again.',
      rule: 'Moving on the phone moves the date of a wedding, a task or a payment. Deleting on the phone does not delete them here, it only unlinks; an entry of yours is deleted on both sides.',
    },
  },

  runsheet: {
    title: 'Day-of schedule',
    back: 'Back to the event',
    print: 'Print / save as PDF',
    audience: 'Who the schedule is for',
    everyone: 'Everyone',
    sheetFor: 'Schedule for:',
    noDate: 'No date set yet',
    empty: 'No day-of schedule has been built yet.',
    emptyForRole: 'No lines are marked for this role. A line with no mark appears for everyone.',
    printedOn: 'Produced on',
    open: 'Day-of schedule',
    owner: 'Owner',
    pastMidnight: '(after midnight)',
    contacts: 'Phone numbers',
    noContacts: 'No phone numbers have been recorded for this event\'s crew and suppliers.',
  },

  numbers: {
    open: 'Numbers sheet',
    title: 'The numbers sheet',
    sub: 'One page with everything a supplier asks: how many, what, and when.',
    back: 'Back to the event',
    print: 'Print / save as PDF',
    counts: 'How many are coming',
    invited: 'Invited',
    attending: 'Confirmed',
    pending: 'No reply yet',
    declined: 'Not coming',
    heads: 'Confirmed heads',
    households: 'Households',
    diet: 'Meals for the caterer',
    dietRegular: 'Regular',
    dietNone: 'No special requests so far.',
    meals: 'meals',
    seating: 'Tables and seating',
    seatingNone: 'No tables defined yet.',
    seatedShort: 'seated',
    seatsShort: 'seats',
    unseated: 'Not seated yet',
    schedule: 'Key moments',
    scheduleNone: 'No key moments on the schedule yet.',
    arrivals: 'Arrival times',
    arrivalsNone: 'No arrival times set yet.',
    updated: 'Correct as of the moment this page was produced. The numbers keep moving until the last minute.',
  },

  guestSite: {
    title: 'Guest site',
    sub: 'One page to send to everyone invited: when, where, the running order, and an RSVP by phone number.',
    on: 'The site is on',
    off: 'The site is off',
    turnOn: 'Turn the site on',
    turnOff: 'Turn the site off',
    link: 'The link to send',
    copy: 'Copy',
    copied: 'Copied',
    open: 'Open',
    share: 'Share on WhatsApp',
    shareText: 'You are invited to celebrate with us! All the details and the RSVP are here:',
    note: 'A few words for the guests',
    notePh: 'Dress code, parking, anything they should know',
    save: 'Save',
    saving: 'Saving',
    saved: 'Saved',
    hint: 'Guests see only the names, the date, the venue, the key moments from the schedule and the words here. Nothing else.',
  },

  statusBoard: {
    noDate: 'No date',
    daysLeft: 'days',
    daysAgo: 'days',
    passed: 'Past',
    next: 'Next:',
    attending: 'coming',
    owed: 'to pay',
    open: 'Open',
    close: 'Close the file',
    reopen: 'Back to active',
    tabLive: 'Active',
    tabDone: 'Closed',
    emptyDone: 'No file has been closed yet. A past event appears here once you close it.',
    allClear: 'All in order. No open gaps on any event.',
  },

  preview: {
    title: 'Couple\'s view',
    banner: 'You are seeing the couple\'s screen',
    exit: 'Back to managing the event',
    open: 'See it as the couple',
    switchesTitle: 'What the couple sees',
    switchesSub: 'Every section of the couple\'s screen is switched on and off here. An open section the couple sees in full and can add to themselves. The budget and payments are locked in the database as well, not only on the screen.',
    coupleSees: 'The couple sees:',
    sharedOn: 'Open to the couple',
    sharedOff: 'Hidden from the couple',
  },

  quickLedger: {
    open: 'Income or expense',
    title: 'Quick entry',
    sub: 'The production\'s own income or expense, in one press, from any screen. An internal record only: it does not issue a receipt or an invoice.',
    income: 'Income',
    expense: 'Expense',
    amount: 'Amount',
    label: 'What for',
    labelPh: 'Tip from the night, a deposit, parking',
    event: 'Which event',
    noEvent: 'No event (yet)',
    party: 'With whom',
    partyPh: 'The couple or supplier, when there is no file',
    date: 'Date',
    note: 'Note',
    save: 'Record',
    saving: 'Recording',
    saved: 'Recorded',
    failed: 'Not recorded. Try again.',
    badAmount: 'The amount has to be a number above zero',
    needLabel: 'What is it for?',
    listTitle: 'Quick entries',
    listSub: 'Income and expenses recorded from the plus. Not part of the event\'s bottom line, and no receipt is issued.',
    listNone: 'Nothing recorded yet.',
    totalIn: 'In',
    totalOut: 'Out',
    net: 'Net',
    unattached: 'No file',
    remove: 'Delete',
  },

  clientPage: {
    back: 'Back to events',
    details: 'Event details',
    rename: 'Edit the name and details',

    tabs: {
      overview: 'Overview',
      tasks: 'Tasks',
      day: 'Schedule',
      guests: 'Guests',
      details: 'Event file',
      crew: 'Crew and suppliers',
      bar: 'Bar',
      money: 'Money',
      docs: 'Documents',
      files: 'Files and photos',
      meetings: 'Meetings',
      messages: 'Messages',
      board: 'Inspiration',
      prep: 'Photo prep',
      venues: 'Venues',
    },

    edit: 'Edit details',
    editSave: 'Save',
    editSaving: 'Saving',
    editCancel: 'Cancel',
    noDateYet: 'No date set yet',
    contact: {
      phone: 'Phone',
      email: 'Email',
      brief: 'What the enquiry said',
    },
    setDate: 'Set a date',
    daysLeft: 'days to the event',
    today: 'The event is today',
    tomorrow: 'The event is tomorrow',
    passed: 'The event was',
    daysAgo: '{n} days ago',

    at: {
      guests: 'Guests',
      confirmed: 'confirmed',
      pending: 'no reply',
      declined: 'not coming',
      seats: 'heads',
      paid: 'Paid',
      owed: 'Still to collect',
      overdue: 'Overdue',
      tasksOpen: 'Open tasks',
      dayLines: 'Schedule lines',
      contracts: 'Signed documents',
      none: '·',
    },

    nextUp: 'Up next',
    nextUpNone: 'No open task or waiting payment right now.',
    openTab: 'Open',

    access: 'Who enters the couple\'s area',
    accessSub: 'Up to three addresses, each with its own way into the same event. Sign-in is with the address itself, by one-time code, no password.',
    accessNone: 'No address attached yet. Until you attach one, the couple has no way in.',
    invitePh: 'Email address',
    invite: 'Attach and invite',
    inviting: 'Sending',
    invited: 'The invitation was sent',
    revoke: 'Remove',
    joined: 'Signed in',
    pendingJoin: 'Not signed in yet',
    full: 'All three addresses are taken. Remove one to attach another.',
    notFound: 'The event was not found.',
  },
};

export const leadEn: LeadCopy = {
  statuses: { new: 'New', contacted: 'Contacted', meeting: 'Meeting set', won: 'Closed', lost: 'Not relevant' },
  note: 'Note',
  notePh: 'What was agreed',
  saveNote: 'Save',
  convert: 'Open an event from this lead',
  callTitle: 'Follow-up call',
  callWhen: 'Remind me on',
  callBook: 'Set a reminder',
  callBooking: 'Setting',
  callsTitle: 'Follow-up calls',
  callsNone: 'No open follow-up calls.',
  callDone: 'Done',
  callReopen: 'Reopen',
  callToday: 'Today',
  callLate: 'Overdue',
  open: 'Open',
  close: 'Close',

  add: 'An enquiry I received',
  addTitle: 'Record an enquiry',
  addSub: 'A call, a message or a referral that reached you directly. Goes into the same list as an enquiry from the site, so it does not stay in a notebook.',
  addName: 'Name',
  addPhone: 'Phone',
  addEmail: 'Email',
  addKind: 'Kind of event',
  addDate: 'Approximate date',
  addGuests: 'Number of guests',
  addMessage: 'What was said',
  addMessagePh: 'A wedding in August, heard of us from friends',
  addHow: 'How they reached us',
  addLocation: 'Event location',
  addLocationFree: 'Or the venue\'s name',
  addLocationPh: 'Venue name or address, if known',
  location: 'Location',
  addSave: 'Save',
  addSaving: 'Saving',
  addCancel: 'Cancel',
  addNeedContact: 'A phone or an email is needed',
  addNeedName: 'Please enter a name',
  addFailed: 'Could not save the enquiry',

  sources: {
    site: 'From the site',
    phone: 'Phone call',
    whatsapp: 'WhatsApp',
    instagram: 'Instagram',
    facebook: 'Facebook',
    meta: 'Meta',
    google_ads: 'Google',
    referral: 'Referral',
    walk_in: 'Came to us',
    webhook: 'Connected system',
  },
};

export const crewEn: CrewCopy = {
  title: 'Event crew',
  sub: 'Who is working the evening, when they arrive and how to reach them. The couple does not see this screen.',
  none: 'No crew assigned yet.',
  add: 'Add a crew member',
  close: 'Close',
  name: 'Name',
  role: 'Role',
  rolePh: 'Lighting',
  phone: 'Phone',
  callTime: 'Arrival time',
  fee: 'Fee',
  feePh: '₪',
  notes: 'Note',
  save: 'Save',
  saving: 'Saving',
  cancel: 'Cancel',
  edit: 'Edit',
  remove: 'Remove',
  totalFee: 'Total crew fees',
  noTime: 'No time',
  privateNote: 'Crew and fees are visible to the producer only.',
};

export const vendorEn: VendorCopy = {
  eventTitle: 'Suppliers on the event',
  eventSub: 'Who is closing what. Phone numbers and status, in one place.',
  eventNone: 'No suppliers assigned yet.',
  add: 'New supplier for the event',
  fromDirectory: 'From my suppliers',
  bookIt: 'Assign',
  close: 'Close',
  name: 'Supplier name',
  category: 'Category',
  contact: 'Contact',
  phone: 'Phone',
  email: 'Email',
  area: 'Area',
  notes: 'Notes',
  callTime: 'Arrival time',
  status: 'Status',
  save: 'Save',
  saving: 'Saving',
  cancel: 'Cancel',
  edit: 'Edit',
  remove: 'Remove',
  saveToDirectory: 'Save to my suppliers',
  inDirectory: 'Saved',
  privateNote: 'The supplier list is visible to the producer only.',

  dirTitle: 'My suppliers',
  hq: {
    title: 'Supplier status',
    sub: 'One row per supplier: contract, deposit, balance, when we last spoke, and whose turn it is. Green when everything is current, amber when you owe a reply, red when a payment or a signature is due within a week or a supplier has been silent for over two weeks.',
    subCouple: 'Where each supplier stands: contract, deposit, balance, and what happens this week.',
    none: 'No suppliers on the event yet. A supplier ticked in the tasks or booked below appears here.',
    colVendor: 'Supplier',
    colContract: 'Contract',
    colDeposit: 'Deposit',
    colBalance: 'Balance',
    colLast: 'Last spoke',
    colTurn: 'Whose turn',
    colAction: 'This week',
    contract: { signed: 'Signed', pending: 'Sent, waiting', none: 'Not sent' },
    deposit: { paid: 'Paid', pending: 'Pending', notDue: 'Not yet due', none: 'Not set' },
    turn: { me: 'Mine', them: 'Theirs', none: 'Nothing open' },
    never: 'Not recorded',
    daysAgo: { one: 'Yesterday', many: '{n} days ago' },
    today: 'Today',
    noPrice: 'No price',
    dueOn: 'By {date}',
    actions: {
      sendContract: 'Send the contract to sign',
      chaseContract: 'Chase the signature',
      payDeposit: 'Pay the deposit',
      payBalance: 'Pay the balance',
      nudge: 'Write again, they went quiet',
      reply: 'Reply to them',
      own: '',
      wait: 'Wait',
    },
    flags: {
      balanceSoon: 'Balance within a week',
      depositSoon: 'Deposit open after signing',
      silent: 'Silent for over two weeks',
      noContract: 'Booked without a contract',
      contractPending: 'Contract unsigned',
      noPrice: 'Booked without a price',
    },
    spoke: 'We spoke today',
    setTurn: 'Whose turn',
    edit: 'Details',
    close: 'Close',
    depositAmount: 'Deposit amount',
    depositPaidOn: 'Deposit paid on',
    balanceDueOn: 'Balance due by',
    nextAction: 'What to do this week, in your words',
    nextActionPh: 'Empty: the system suggests from the state',
    save: 'Save',
    saving: 'Saving',
    weekTitle: 'This week\'s list',
    weekSub: 'Every red or amber row, what to do, and the message that clears it. Copy, fix a word, send.',
    weekNone: 'Nothing to clear this week. Every supplier is green.',
    copy: 'Copy',
    copied: 'Copied',
    whatsapp: 'WhatsApp',
    riskTitle: 'Three to keep an eye on',
    riskSub: 'The relationships most likely to blow up: long silence, missing contract, big balance.',
    riskNone: 'No relationship at risk right now.',
    riskWhy: {
      silent: 'No reply for {n} days.',
      noContract: 'Booked without a signed contract.',
      balance: 'A balance of {amount} is still open.',
      fine: 'Nothing urgent, just the most exposed on the list.',
    },
    summaryTitle: 'In four lines',
    locked: 'Suppliers locked with a signed contract: {n} of {total}',
    depositsPaid: 'Deposits paid: {n}',
    dueSoon: 'Balances due within thirty days: {amount}',
    biggest: 'The one thing to do this week: {what}',
    biggestNone: 'The one thing to do this week: nothing. All green.',
    mondayNote: 'Every Monday morning these four lines reach you by email and in the bell, for every open event.',
  },
  scout: {
    title: 'Supplier scout for an event',
    sub: 'Five of your own suppliers who best fit one couple: by the style in their words, by the budget, and by how often you have worked together. With an outreach message ready to send.',
    open: 'Scout suppliers for an event',
    close: 'Close',
    category: 'Which supplier',
    event: 'Which event',
    noEvent: 'No event',
    style: 'The style, in the couple\'s words',
    stylePh: 'warm, natural, candid',
    area: 'Area',
    areaPh: 'North, centre, Jerusalem',
    budget: 'Budget for this supplier',
    low: 'From',
    high: 'To',
    dealBreakers: 'Deal-breakers',
    dealBreakersPh: 'Hour minimums, filters, travel',
    run: 'Rank',
    none: 'No supplier in this category in the directory. Add one above, or import from Excel.',
    colStyle: 'Style',
    colBudget: 'Budget',
    colStrength: 'Track record',
    outOf: 'out of 30',
    bookings: { one: 'One event with you', many: '{n} events with you' },
    neverBooked: 'Not worked together yet',
    noPrice: 'No price on the card',
    why: 'Matches: {words}',
    whyNone: 'Nothing on the card echoes the style you asked for. Worth filling in the notes.',
    flags: 'Note: {words}',
    inArea: 'In the area',
    outreachTitle: 'Outreach message for the first on the list',
    outreachSub: 'With the date, venue, guest count and budget from the event. The line in brackets is yours: one detail from their work, and it is no longer a template.',
    genericTitle: 'The same message for the other four',
    copy: 'Copy',
    copied: 'Copied',
    whatsapp: 'Open in WhatsApp',
    bestWeekNow: 'A good time to send: today. Suppliers drown on Sunday and Monday; Tuesday to Thursday gets read.',
    bestWeekNext: 'A good time to send: Tuesday to Thursday, {from} to {to}. On Sunday and Monday suppliers drown.',
    honest: 'The ranking is from your own directory only. The system does not scan Instagram or review sites.',
  },
  dirSub: 'The notebook that stays between events. A supplier saved here is assigned to the next event in one press, without typing the number again.',
  dirNone: 'No suppliers saved yet.',
  dirAdd: 'Add a supplier',
  dirSearch: 'Find a supplier',
  dirSearchPh: 'Name, category or area',
  dirActive: 'Active',
  dirArchived: 'Archived',
  archive: 'Archive',
  unarchive: 'Restore',
  count: '{n} suppliers',
  noResults: 'No matching supplier.',
  allCategories: 'All categories',
  agreedPrice: 'Agreed price',
  depositPaid: 'Deposit paid',

  import: {
    open: 'Import from Excel',
    title: 'Import suppliers from Excel',
    sub: 'An Excel or CSV file with the columns: supplier name, category, phone, email, agreed price, deposit paid, notes. The first row is the headings.',
    template: 'Download a template',
    templateName: 'suppliers-template.xlsx',
    choose: 'Choose a file',
    drop: 'Drag an xlsx, xls or csv file here',
    reading: 'Reading the file',
    unreadable: 'Could not read the file. Try saving it again as xlsx.',
    noRows: 'No rows with a supplier name were found.',
    mapping: 'Match the columns',
    mappingSub: 'The columns were recognised by their headings. You can correct them here before importing.',
    skip: 'Do not import',
    preview: 'What will come in',
    previewMore: 'and {n} more rows',
    rowsFound: '{n} suppliers in the file',
    willAdd: '{n} new',
    willUpdate: '{n} existing will be updated',
    run: 'Import',
    running: 'Importing',
    done: 'Import complete',
    added: 'Added',
    updated: 'Updated',
    skipped: 'Skipped',
    failed: 'The import failed. Try again.',
    cancel: 'Cancel',
    columns: {
      name: 'Supplier name',
      category: 'Category',
      phone: 'Phone',
      email: 'Email',
      agreed_price: 'Agreed price',
      deposit_paid: 'Deposit paid',
      notes: 'Notes',
      contact_name: 'Contact',
      area: 'Area',
    },
  },
};

export const templateEn: TemplateCopy = {
  title: 'Ready-made event file',
  sub: 'The lists you work to. Choose what goes into this event, and for each task decide whether the couple sees it.',
  tasksTab: 'Tasks',
  budgetTab: 'Budget',
  suppliersTab: 'Suppliers',
  pickAll: 'Select all',
  pickNone: 'Clear',
  shared: 'Couple sees',
  sharedOn: 'Shared',
  sharedOff: 'Private',
  apply: { one: 'Add one line', many: 'Add {n} lines' },
  applying: 'Adding',
  nothing: 'Nothing selected',
  added: '{n} added. Each one can be edited.',
  privateNote: 'A private task does not appear for the couple, not in their area and not in notifications.',
  open: 'Add from the template',
  close: 'Close',
};

export const barEn: BarCopy = {
  title: 'Bar calculator',
  sub: 'How many bottles, how much ice, and what it costs. A starting point for negotiating with the supplier, not a quote.',
  guests: 'Guests',
  children: 'Percent children',
  childrenHint: 'No alcohol, and everything else',
  drinkers: 'Percent of adults who drink',
  drinkersHint: 'The number that moves the result more than anything else',
  hours: 'Hours the bar is open',
  hoursHint: 'Not the length of the evening. The bar closes before the last song',
  style: 'Drinking style',
  season: 'Season',
  styles: {
    house: 'My calculation',
    classic: 'Mixed',
    spirits: 'Spirits',
    wine: 'Wine',
    beer: 'Beer',
    light: 'Light',
  },
  seasons: { summer: 'Summer', mild: 'Spring or autumn', winter: 'Winter' },

  planTitle: 'What to buy',
  drinkersOut: 'drinkers',
  servingsOut: 'servings',
  litresOut: 'litres of alcohol',
  houseNote: 'By your rule: a litre for every nine people, in your fixed split. Bar hours do not change the quantity in this method, because they are already in the number.',
  items: {
    vodka: 'Vodka', whiskey: 'Whisky', gin: 'Gin', other: 'Liqueurs and other',
    campari: 'Campari', tequila: 'Tequila', rum: 'Rum',
    wine: 'Wine', beer: 'Beer', soft: 'Soft drinks', ice: 'Ice',
    citrus: 'Lemons and limes', cups: 'Cups',
  },
  units: {
    vodka: 'bottles', whiskey: 'bottles', gin: 'bottles', other: 'bottles',
    campari: 'bottles', tequila: 'bottles', rum: 'bottles',
    wine: 'bottles', beer: 'units', soft: 'litres', ice: 'kg',
    citrus: 'units', cups: 'units',
  },
  beerUnit: 'Beer count',
  beerAsBottles: '330ml bottles',
  beerAsPacks: 'Six-packs',
  beerPackNote: 'The same amount of beer, counted the way it is bought. The litres do not change.',
  unitPrice: 'Price per unit',
  lineTotal: 'Total',
  grandTotal: 'Estimated total',
  prices: 'Prices',
  pricesHint: 'Your prices, not ours. Change them and what is below updates.',
  print: 'Print the shopping list',
  assumptions: 'How it was calculated',
  assumptionLines: [
    'Two servings per drinker in the first hour, one every hour after. People arrive thirsty and then settle.',
    'A bottle of spirits is 15 servings and not 17, because a hurried hand is generous. Wine is 5 glasses.',
    'Ice by guest and not by hour, because the bottles and the fish need it too.',
    'We chose to err upwards on ice and downwards on alcohol. A bar without ice is over at eleven; a leftover bottle of vodka goes home with somebody.',
    '"My calculation" is the rule from your spreadsheet and we did not touch it. The rest is a model by servings, which answers "and what if the bar is open two hours longer".',
  ],
};

export const updateEn: UpdateCopy = {
  ready: 'There is a new version of the system',
  refresh: 'Refresh',
};

export const linkEn: LinkCopy = {
  make: 'Signing link',
  making: 'Creating',
  ready: 'The link is ready. Send it to the supplier on WhatsApp or by email.',
  copy: 'Copy',
  copied: 'Copied',
  whatsapp: 'Send on WhatsApp',
  revoke: 'Revoke the link',
  revokeNote: 'Revoking the link closes the door; it does not cancel a signature already made.',
  failed: 'Could not create a link. Try again.',
};

export const signEn: SignCopy = {
  eyebrow: 'Agreement for signature',
  badLink: 'This link is no longer active',
  badLinkBody: 'The agreement may have been signed, the link replaced, or copied incompletely. Contact whoever sent it and ask for a new link.',
  amount: 'Amount',
  file: 'View the attached file',
  nameLabel: 'Your full name',
  namePh: 'As it should appear on the agreement',
  sign: 'I have read and I agree',
  signing: 'Signing',
  before: 'Pressing the button is a signature. From that moment the terms above cannot be changed, not by you and not by the sender.',
  doneTitle: 'Signed',
  doneBy: 'Signed by',
  doneAt: 'On',
  doneBody: 'Keep this link. It will keep showing the signed agreement and the time of signing.',
  short: 'Please sign with your full name',
  failed: 'The signature did not go through. Try again, and if it keeps happening contact whoever sent the link.',
};

export const siteEditorEn: SiteEditorCopy = {
  title: 'Edit the site',
  sub: 'The words on the public site. A change is saved and published at once, with no deploy.',
  sections: 'Sections',
  save: 'Save',
  saving: 'Saving',
  saved: 'Saved',
  wasReset: 'Restored to the original',
  unsaved: 'There is an unsaved change',
  reset: 'Restore the original wording',
  edited: 'Edited',
  note: 'What does not appear here stays fixed in the code. A field that is cleared goes back to the wording it was written with.',
};

export const hebrewCalEn: HebrewCalCopy = {
  title: 'Hebrew calendar and holidays',
  sub: 'Which evenings in the next thirty days are free for a wedding, and which are closed by halacha.',
  next30: '30 days',
  next60: '60 days',
  clear: 'Free',
  check: 'Check',
  blocked: 'Restricted for a halachic wedding',
  clearLegend: 'Free evening',
  checkLegend: 'Depends on custom',
  blockedLegend: 'No weddings held',
  today: 'Today',
  hebrewOn: 'Begins at nightfall',
  none: 'No days in this range.',
  disclaimer: 'This is a planning aid and not a ruling. Customs differ between communities, and any borderline date is settled with the couple\'s rabbi.',
  custom: 'The custom shown here is the common Ashkenazi one in Israel. In the Sephardi custom the Omer restrictions run until Lag BaOmer.',
  reasons: {
    shabbat: 'Shabbat',
    erevShabbat: 'Friday evening',
    roshHashana: 'Rosh Hashanah',
    yomKippur: 'Yom Kippur',
    sukkot: 'Sukkot',
    cholHamoed: 'Chol HaMoed',
    shminiAtzeret: 'Shemini Atzeret and Simchat Torah',
    pesach: 'Passover',
    shavuot: 'Shavuot',
    erevChag: 'Eve of a holiday',
    threeWeeks: 'The Three Weeks',
    nineDays: 'The Nine Days',
    tishaBav: 'Tisha B\'Av',
    omer: 'The Omer',
    omerSephardi: 'Omer, Sephardi custom',
    lagBaomer: 'Lag BaOmer',
    fast: 'Fast day',
    purim: 'Purim',
    roshChodesh: 'Rosh Chodesh',
  },
};

export const labelEn: LabelCopy = {
  tagsTitle: 'My colours',
  tagsSub: 'What each colour means in your calendar. You can rename, recolour, and add your own.',
  channelsTitle: 'My enquiry channels',
  channelsSub: 'How enquiries reach you. What you add here appears in the enquiry form and the channels report.',
  add: 'Add',
  addPh: 'Tag name',
  addChannelPh: 'Channel name',
  save: 'Save',
  saving: 'Saving',
  rename: 'Rename',
  color: 'Colour',
  remove: 'Delete',
  none: 'None defined yet.',
  noneChannels: 'You have not added a channel of your own yet. Six built-in channels already exist.',
  builtIn: 'Built in',
  taken: 'You already have one by that name.',
  failed: 'Could not save. Try again.',
  tooLong: 'That name is too long. Up to 40 characters.',
  needName: 'Please write a name.',
  close: 'Close',
  eventTag: 'Event tag',
  eventTagNone: 'No tag',
  legend: 'Legend',
};

export const knowledgeEn: KnowledgeCopy = {
  title: 'Knowledge',
  sub: 'How to work in the system, how to produce an event, and what you have already built for yourself.',
  shelves: {
    book: 'Using the system',
    playbook: 'The production book',
    templates: 'Your templates',
  },
};

export const jumpEn: JumpCopy = {
  open: 'Quick search',
  title: 'Where to?',
  placeholder: 'Name of an event, lead, supplier or screen',
  screens: 'Screens',
  events: 'Events',
  leads: 'Leads',
  vendors: 'Suppliers',
  recent: 'Recent',
  sections: 'Section inside an event',
  none: 'Not found. Try part of the name.',
  close: 'Close',
  hint: 'Arrows to choose, Enter to open, Esc to close.',
  hintTwo: 'An event name together with a section name opens the section directly.',
};

export const copilotEn: CopilotCopy = {
  open: 'Producer assistant',
  close: 'Close',
  title: 'Producer assistant',
  sub: 'Knows the open event, the schedule and the operating book.',
  context: 'In context',
  noContext: 'All events',
  greeting: 'You can ask me to draft an email to a supplier, an update to the couple on WhatsApp, an agenda for a meeting, or ask what is left to do before the event.',
  starters: [
    'Draft an email to a supplier with the arrival time',
    'A short update to the couple on the schedule',
    'What is left to do before the event?',
    'Which confirmations am I still missing from suppliers?',
    'Which payments are open and when',
    'Summarise the overdue tasks for me',
    'An agenda for a coordination meeting',
    'A questionnaire for a tasting meeting',
    'A short briefing for the crew on the day',
  ],
  read: 'I read',
  reads: {
    tasks: 'tasks',
    payments: 'payments',
    vendors: 'suppliers',
    budget: 'budget lines',
    guests: 'guests',
    schedule: 'schedule lines',
  },
  placeholder: 'What do you need?',
  send: 'Send',
  thinking: 'One moment',
  copy: 'Copy',
  copied: 'Copied',
  whatsapp: 'Send on WhatsApp',
  wentWrong: 'Something got stuck on my side. Try again in a moment.',
  disclaimer: 'Drafts to edit. Read before you send.',
};

export const archiveEn: ArchiveCopy = {
  title: 'Archive',
  sub: 'Closed events, by the year they took place.',
  open: 'Archive',
  backToLive: 'To the active events',
  yearLabel: 'Events of {year}',
  noYear: 'No date',
  count: { one: 'One event', many: '{n} events' },
  empty: 'No event has been closed here yet.',
  emptyYear: 'No events in that year.',

  close: 'Close the event',
  closing: 'Closing',
  closeAsk: 'Close the event? A snapshot of the suppliers, the crew and the money as they are now will be kept.',
  closeNote: 'Closing note',
  closeNotePh: 'What is worth remembering from this evening',
  reopen: 'Reopen',
  reopened: 'The event is back among the active ones',
  closeNote2: 'The snapshot kept at closing stays even if you reopen the event.',

  frozen: 'Snapshot from closing',
  vendors: 'Suppliers',
  crew: 'Crew',
  money: 'Money',
  runsheet: 'Schedule',
  guestsFinal: 'Guests who came',
  budget: 'Budget',
  paid: 'Paid',
  closedOn: 'Closed on',

  anniversary: 'A year after the event',
  anniversarySub: 'A reminder is sent a month, a week and a day before. Only in the first year.',
  anniversaryCancel: 'Cancel the reminder',
  yearSince: 'A year since',
  anniversaryIn: {
    month: 'in a month',
    week: 'in a week',
    day: 'tomorrow',
    today: 'today',
    passed: 'passed',
  },
  greet: 'Send a greeting',
};

export const meetingEn: MeetingCopy = {
  title: 'Meetings',
  sub: 'What was asked, what was answered, and what was agreed. Every version is kept.',
  none: 'No meeting has been written up yet.',
  add: 'Write up a meeting',
  pick: 'Which meeting',
  held: 'Meeting date',
  save: 'Save',
  saving: 'Saving',
  cancel: 'Cancel',
  remove: 'Delete',
  removeAsk: 'Delete this meeting write-up?',
  open: 'Open',
  close: 'Close',

  summary: 'Summary',
  summarise: 'Write a summary',
  summarising: 'Writing',
  summaryByModel: 'The paragraph at the top was written automatically. The record underneath is what was noted in the meeting.',
  summaryNone: 'Nothing to summarise yet. Fill in a few fields and save.',
  answered: '{filled} of {total} answered',
  shareWithCouple: 'Shared with the couple',
  shareHint: 'By default a meeting stays with you only.',
  versions: 'Versions',
  versionsNone: 'This is the first version.',
  savedAt: 'Saved',
  saveFailed: 'Could not save',
  builtIn: 'The standing meetings',
  own: 'Your templates',
  buildOwn: 'Build a template of your own',
  noForm: 'The template this meeting was written from no longer exists. The summary remains.',
  blank: 'Blank page',
  blankWhen: 'No questions, just write',
  openNote: 'Open the page',
};

export const noteEn: NoteCopy = {
  title: 'Blank page',
  titlePh: 'A title, if you want one',
  bodyPh: 'Write here.',
  held: 'Date',
  back: 'Back to the event',
  done: 'Done',
  saving: 'Saving',
  saved: 'Saved',
  savedAt: 'Saved at {at}',
  unsaved: 'Not saved yet',
  failed: 'Could not save. Trying again in a moment.',
  restored: 'Restored what was written and had not been saved.',
  nearLimit: '{n} characters left on this page.',
  full: 'The page is full. Worth opening a new one.',
};

export const workflowEn: WorkflowCopy = {
  title: 'Workflow templates',
  sub: 'Lists that repeat on every event. Applied to the wedding date and spread across the schedule.',
  none: 'You have not built a template yet.',
  add: 'New template',
  seed: 'Start from the four meetings',
  name: 'Template name',
  namePh: 'My way to a wedding',
  steps: 'Steps',
  stepTitle: 'What to do',
  stepWhen: 'How many days before the wedding',
  stepWhenHint: 'A positive number. 90 is three months before.',
  stepOwner: 'Whose',
  ownerProducer: 'Mine',
  ownerClient: 'The couple\'s',
  addStep: 'Add a step',
  removeStep: 'Remove',
  save: 'Save',
  saving: 'Saving',
  cancel: 'Cancel',
  remove: 'Delete',
  removeAsk: 'Delete this template?',
  onThisEvent: 'A list for this event',
  which: 'Which template',
  stepsCount: { one: 'One step', many: '{n} steps' },
  apply: 'Apply to an event',
  applying: 'Applying',
  applied: { none: 'Everything was already there', many: '{n} steps added' },
  noDate: 'The event has no date yet, so the steps will come in without a due date.',
  saveFailed: 'Could not save',
};

export const referralEn: ReferralCopy = {
  title: 'Referrals',
  sub: 'Who joined through whom. Numbers only, with no couple\'s name and no event\'s name.',
  myLink: 'My link',
  copy: 'Copy',
  copied: 'Copied',
  producer: 'Producer',
  code: 'Code',
  invitedBy: 'Joined through',
  invited: 'Brought',
  clients: 'Events',
  direct: 'Directly',
  none: 'Nobody has joined through a link yet.',
  claim: 'I joined through a code',
  claimPh: 'The code you received',
  claimSave: 'Link it',
  claimed: 'The link was saved',
  claimFailed: 'The code was not found, or you are already linked.',
};
